### ISSUE TITLE
Latest database-refactor has introduced multiple [WMWARN33] warning msgs into the Cacti Log

### ISSUE THREAD

**Issue by taharg** [howardjones/network-weathermap#100]
After an update with the latest database-refactor branch,
multiple [WMWARN33] appear in cacti log.

WEATHERMAP WARNING: [Map 6] xxxxx.conf: ColourFromValue: Clipped 37842.771970622% to 100% for item node08523-node08523_copy [WMWARN33]
2017-05-29 09:10:15 - WEATHERMAP WARNING: [Map 6] xxxxxx.conf: ColourFromValue: Clipped 4598.0824432018% to 100% for item node08523-node08523_copy [WMWARN33]
2017-05-29 09:10:15 - WEATHERMAP WARNING: [Map 6] Illustration3.conf: ColourFromValue: Clipped 4730.3464963277% to 100% for item node02710-node08523_copy [WMWARN33]
2017-05-29 09:10:15 - WEATHERMAP WARNING: [Map 6] Illustration3.conf: ColourFromValue: Clipped 574.76030540022% to 100% for item node02710-node08523_copy [WMWARN33]
2017-05-29 09:10:15 - WEATHERMAP WARNING: [Map 6] Illustration3.conf: ColourFromValue: Clipped 591.29331204096% to 100% for item node01296-ill_wm [WMWARN33]
 
On the maps, the reported values doesn't seem to be the good one.

**Comment by howardjones** [comment]
Please run with debug logging, and look for the ReadData lines for these targets. That will tell you (and me) what data is being collected from the target. Please also share the config for one of these nodes (to show maxvalue and targets).

**Comment by howardjones** [comment]
(maybe the same as #93 but not enough info on either case to confirm)

**Comment by ikorzha** [comment]
It is definitely same issue, I was unable to do a debug because of my big prod installation.

**Comment by howardjones** [comment]
I've just pushed a new commit that might be related. In the rrdtool plugin (and maybe others), if one target succeeds and the next one fails, the failing one could end up with the data for the previous target.

https://forum.network-weathermap.com/t/rrdtool-aggregate-target-has-no-valid-data-after-move-to-github-version/76/12

This might explain why you are getting larger values than you expect. However it would be best to try and get the logs as there are several possible failures here: data collection, the scale processing, the configured maxvalue, or your expectations of the data.

**Comment by taharg** [comment]
Thank you very much;
the latest update solve this issue for me.

**Comment by howardjones** [comment]
Cool! I need to figure out some automated testing for these things... that's the best way to stop it re-occurring.

**Comment by ikorzha** [comment]
I do confirm the issue as resolved, Howie, please close it.  No more Warn29 and 33.
