### ISSUE TITLE
Missing files on the /vendor directory

### ISSUE THREAD

**Issue by hadeshimself** [howardjones/network-weathermap#101]
There are a few files missing on the /vendor directory. There's a wrong reference to jquery.min.js and there's no jquery-fastlivefilter included.

**Comment by howardjones** [comment]
Please read the README.md

**Comment by hadeshimself** [comment]
Sorry about that. But yes, after that the files are not going automatically to the /vendor directory. They stayed at bower_components/. Moving them makes everything work fine.

**Comment by howardjones** [comment]
Hmm. When you did the git clone, you should have gotten a '.bowerrc' file that corrects that (to make bower install modules in vendor instead of bower_components) - did that file not come down with the rest?

**Comment by hadeshimself** [comment]
Correct, that fixes it. I somehow messed up with the file permissions on all dot files.

**Comment by howardjones** [comment]
OK, cool. Just wanted to make sure I didn't accidentally do something there :-) I've also just removed the 'other' copies for jquery etc, so it's more obvious that it should all be in vendor. This is only a problem if you are tracking the dev version though.
