### ISSUE TITLE
Enchancement request: Group Based Map Cycling, that previously existed in old SVN.

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#103]
I would like to request to bring back very useful feature from old SVN "Group Based Map Cycling."  I have used it extensively, and it helps to prevent cycling of irrelevant maps, that particular user might have access to.
Below is screenshot of dialog box of what it looked like in Weathermap tab.
![group-cycle](https://cloud.githubusercontent.com/assets/11211789/26584641/8440a8b6-4517-11e7-9eec-b7eea0088f9a.jpg)

**Comment by howardjones** [comment]
I don't have enough maps loaded to test properly, but it seems that this link already appears for any group except for the original 'Weathermaps' group 1... so it's more a bug than a feature request :-)

**Comment by howardjones** [comment]
Actually, for 0.8.8, it depends on how many maps are in the group. A group with a single map is always shown full size, and that uses different code. The thumbnail view doesn't include the link for 'limit to group', but the full-size view does.

I forgot to add the issue tag, but I just pushed a small commit that I think fixes this. I'm not able to test fully right now.

**Comment by ikorzha** [comment]
I have just finished testing with the latest patch. Map cycling per group works as designed! Thank you very much! I will close the request.
