### ISSUE TITLE
PHP Source File '/var/www/html/plugins/weathermap/Tests/WeathermapManagerTest.php' from Cache has a Syntax error! 

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#109]
I am testing a Cacti 1.0 feature remote polling.  Polling of remote devices functions.  What I have ran into is that when I look into remote poller log I get the following msg on every poller cycle (every min).

2017/06/08 15:35:02 - POLLER: Poller[3] ERROR: PHP Source File '/var/www/html/plugins/weathermap/Tests/WeathermapManagerTest.php' from Cache has a Syntax error!

**Comment by howardjones** [comment]
Huh? That isn't even part of the normal code!

What happens if you delete the Tests/ directory? It's not need to run weathermap.

**Comment by ikorzha** [comment]
Howie, never mind, I  UN-unstalled weathermap from main server removed, tests folder, reinstalled all good.
Thank you for your guidance.
