### ISSUE TITLE
Plugin 'weathermap': Division by zero    DB-Refactor Branch under Cact 1.1.10

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#110]
Getting the following errors in Cacti Log...
Errors in logs occurred when I was re-assigning devices from main poller to a remote poller.  Hope that info helps.

2017/06/08 21:49:03 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 533 process_poller_output)(/lib/poller.php: 492 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 weathermap_poller_output)(/plugins/weathermap/lib/cacti-plugin-poller.php: 99 CactiErrorHandler)(/lib/functions.php: 4361 cacti_debug_backtrace)
2017/06/08 21:49:03 - ERROR PHP WARNING in Plugin 'weathermap': Division by zero in file: /var/www/html/plugins/weathermap/lib/cacti-plugin-poller.php on line: 99
2017/06/08 21:49:03 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 533 process_poller_output)(/lib/poller.php: 492 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 weathermap_poller_output)(/plugins/weathermap/lib/cacti-plugin-poller.php: 99 CactiErrorHandler)(/lib/functions.php: 4361 cacti_debug_backtrace)
2017/06/08 21:49:03 - ERROR PHP WARNING in Plugin 'weathermap': Division by zero in file: /var/www/html/plugins/weathermap/lib/cacti-plugin-poller.php on line: 99
2017/06/08 21:49:03 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 533 process_poller_output)(/lib/poller.php: 492 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 weathermap_poller_output)(/plugins/weathermap/lib/cacti-plugin-poller.php: 99 CactiErrorHandler)(/lib/functions.php: 4361 cacti_debug_backtrace)
2017/06/08 21:49:03 - ERROR PHP WARNING in Plugin 'weathermap': Division by zero in file: /var/www/html/plugins/weathermap/lib/cacti-plugin-poller.php on line: 99
2017/06/08 21:49:03 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 533 process_poller_output)(/lib/poller.php: 492 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 weathermap_poller_output)(/plugins/weathermap/lib/cacti-plugin-poller.php: 99 CactiErrorHandler)(/lib/functions.php: 4361 cacti_debug_backtrace)
2017/06/08 21:49:03 - ERROR PHP WARNING in Plugin 'weathermap': Division by zero in file: /var/www/html/plugins/weathermap/lib/cacti-plugin-poller.php on line: 99 

![errors](https://user-images.githubusercontent.com/11211789/26957729-fb08b0c2-4c94-11e7-9d03-f2ee423b6d09.jpg)

**Comment by howardjones** [comment]
So just to be clear - are you also using poller_output ("boost") mode in your maps?

I haven't actually tried multiple pollers at all...

**Comment by ikorzha** [comment]
All of my maps use "SET rrd_use_poller_output 1".  In fact cacti documentation states that enabling boost is a requirement in multi poller environments in Cacti 1.x.
I'm not in production yet with muti poller setup so far I'm just testing concept, functionality and working thru bug that I identify in a testing process.  THis installation where errors occurred, doesn't even have any maps, Just a weathermap plugin installed and enabled.

**Comment by howardjones** [comment]
OK, so if I'm following the flow of my own code properly - you have no maps now, but you *did have*, and there are still items in `weathermap_data` that the poller is looking for. `delete from weathermap_data` should resolve that.

I'll add in some more checking here - it seems that in some situations new data arrives without a timestamp, which will be a problem for weathermap.

**Comment by ikorzha** [comment]
Yes, you are absolutely right, no maps now but it used to have them... I went and explored the weathermap_data table, and you are absolutely right it does have "some old data"
![weathermap-data](https://user-images.githubusercontent.com/11211789/26977409-c6285270-4cf5-11e7-8bf1-49037f685307.jpg)

**Comment by howardjones** [comment]
I have not yet figured out an efficient way to decide if the data in weathermap_data is still required by any maps. So if you remove a map, the data that it used to use is still collected by the poller_output handler.

The answer is probably some kind of batch job, but I wanted to avoid having to do a SQL update (on a 'last_read' field) every time a value is used. Maybe the performance hit wouldn't be so bad.

But in the meantime, the quick fix is to truncate that table.

I will investigate some more with multi-server cacti, once single-server cacti is back to normal :-)

**Comment by ikorzha** [comment]
Closing as too old, will test in new version.
