### ISSUE TITLE
Weathermap not showing in plugins.

### ISSUE THREAD

**Issue by pizu** [howardjones/network-weathermap#112]
Files & Folders in Waethermap plugins

[root@localhost weathermap]# ls -lhaG --color=always | sed -re 's/^[^ ]* //'
316K
 16 cacti 4.0K Jun 27 13:25 .
 7 cacti   96 Jun 27 13:38 ..
  1 cacti  666 Jun 27 13:23 bower.json
  1 cacti   29 Jun 27 13:23 .bowerrc
  2 cacti  108 Jun 27 13:23 build
  1 cacti  12K Jun 27 13:23 build.xml
  1 cacti  40K Jun 27 13:23 CHANGES
  1 cacti  392 Jun 27 13:23 .codeclimate.yml
  1 cacti  592 Jun 27 13:23 composer.json
  2 cacti 4.0K Jun 27 13:23 configs
  1 cacti  18K Jun 27 13:23 COPYING
  1 cacti  107 Jun 27 13:23 .csslintrc
  1 cacti  305 Jun 27 13:23 deploy-test-plugin.sh
  1 cacti  675 Jun 27 13:23 dev-bootstrap.sh
  8 cacti  153 Jun 27 13:23 docs
  2 cacti   23 Jun 27 13:23 editcache
  1 cacti  886 Jun 27 13:23 editor-collections.cfg
  1 cacti   16 Jun 27 13:23 .eslintignore
  1 cacti 4.0K Jun 27 13:23 .eslintrc
  8 cacti  163 Jun 27 13:23 .git
  2 cacti   63 Jun 27 13:23 .github
  1 cacti  702 Jun 27 13:23 .gitignore
  2 cacti 4.0K Jun 27 13:23 images
  1 cacti  11K Jun 27 13:23 in2.png
  1 cacti  11K Jun 27 13:23 in3.png
  1 cacti 9.9K Jun 27 13:23 in.png
  1 cacti 3.0K Jun 27 13:23 Makefile
  1 cacti  148 Jun 27 13:23 mk-phpdoc.sh
  1 cacti   38 Jun 27 13:23 net-data.txt
  1 cacti 1.4K Jun 27 13:23 new-dom-structure.txt
  1 cacti 3.3K Jun 27 13:23 newpicker.html
  1 cacti 2.7K Jun 27 13:23 newpickerserver.php
  2 cacti  216 Jun 27 13:23 old-tests
  1 cacti 9.8K Jun 27 13:23 out2.png
  1 cacti 9.9K Jun 27 13:23 out3.png
  1 cacti 9.4K Jun 27 13:23 out.png
  2 cacti   68 Jun 27 13:23 output
  1 cacti  514 Jun 27 13:23 package.json
  1 cacti  14K Jun 27 13:23 packing.list
  1 cacti  150 Jun 27 13:23 packing.list-tests
  1 cacti 2.4K Jun 27 13:23 README.md
  1 cacti 3.9K Jun 27 13:23 scaledummy.png
  4 cacti 4.0K Jun 27 13:23 src
  5 cacti   74 Jun 27 13:23 srcweb
  1 cacti 1.1K Jun 27 13:23 test-config.json
  1 cacti  827 Jun 27 13:23 test.html
  5 cacti   73 Jun 27 13:23 Tests
  1 cacti 1.7K Jun 27 13:23 test.sh
  1 cacti  929 Jun 27 13:23 TESTS-todo.txt
  7 cacti  176 Jun 27 13:23 test-suite
  1 cacti  21K Jun 27 13:23 TODO
  1 cacti  756 Jun 27 13:23 .travis.yml
  1 cacti  416 Jun 27 13:23 update-summaries.sh
  4 cacti   56 Jun 27 13:23 vendor
  1 cacti    8 Jun 27 13:23 VERSION
  1 cacti  370 Jun 27 13:23 weathermap.conf

Screenshot:
![image](https://user-images.githubusercontent.com/7047326/27588574-f21c9632-5b48-11e7-8ddd-847e771c94d3.png)

Using Cacti & Weathermap latest versions.

mysql  Ver 15.1 Distrib 10.1.24-MariaDB, for Linux (x86_64) using readline 5.1

PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

Centos 7 - 3.10.0-514.21.2.el7.x86_64

**Comment by pizu** [comment]
![image](https://user-images.githubusercontent.com/7047326/27595048-d5ade240-5b5b-11e7-817f-13f6c80ee445.png)
![image](https://user-images.githubusercontent.com/7047326/27595073-e9e4c148-5b5b-11e7-8175-b49bccf1db19.png)

**Comment by howardjones** [comment]
That's the master branch. You want the database-refactor branch. Also, please read the Readme.md (in the database-refactor branch) for some extra steps before everything works.

**Comment by pizu** [comment]
Hi,

Thanks for your quick reply :)

So i need to install the latest version 1st (https://github.com/howardjones/network-weathermap/releases)

then install this or?

Thanks.

**Comment by pizu** [comment]
never mind my last comment, installed the database reflector now and did the bower installation but still same :(

**Comment by howardjones** [comment]
Technology I would suggest stay with 0.98 and cacti 0.8. you are using the
latest development version (which does work for other people) so there is
limited support...  also I'm on vacation, so even more limited :-)

**Comment by pizu** [comment]
thanks for your support nw - i will have a test env to do some tests :) mean time i will install 0.98, our live system is on 0.8.8b
