### ISSUE TITLE
Detecting resource change "FIX"  Request to incorporate new INFO file into GITHUB

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#113]
Howie, I have worked extensively with Cacti team and in close cooperation they have introduced a facility in Cacti starting with version 1.1.11 that has an ability to exclude certain folders and and file extensions within plugin itself from new Cacti caching mechanism.  
I have applied and tested the fix in my Cacti 1.1.11 install with weathermap, there are no longer problems where cacti replicates every min output folder, configs files that modified and html/png written to root.  
What is required on your behalf is to update the INFO file on github branch of weathermap with the following line: nosync = configs, output, *.html, *.conf, *.txt, *.png
Full INFO file below, thank you in advance for all your help.

[info]
compat = 1.0.0
author=Howard Jones
homepage=http://www.network-weathermap.com/
webpage=http://www.network-weathermap.com/
longname=Network Weathermap for Cacti 1.x
name=weathermap
version=1.0.0
email=howie@thingy.com
url=http://www.network-weathermap.com/versions.php
nosync = configs, output, *.html, *.conf, *.txt, *.png

**Comment by howardjones** [comment]
Somehow I missed this before. Thanks for researching this change - it's in the master branch now.
