### ISSUE TITLE
Plugin permissions by group does not work @ Cacti 1.x

### ISSUE THREAD

**Issue by jpobeda** [howardjones/network-weathermap#115]
Hi Howie,

I'm running Cacti 1.1.12 and dev version of nwm of course.

What doesn't work is when I try to give access to the plugin by groups. 
I don't know if this is intended to work or not, let me know. I

f I set access by user, it does work. I'm not talking about Map access but Weathermap plugin itself.

Have a look at this issue for Audit Plugin, https://github.com/Cacti/plugin_audit/issues/1

Let me know if you need further details.

**Comment by howardjones** [comment]
Hi Javier, I'm on vacation right now (actually in your timezone for once!)
so can't easily check, but there is nothing special in weathermap to deal
with groups, and the access checking is done by Cacti as far as I remember.
Should have some time to look further next week.

**Comment by jpobeda** [comment]
hehehe you're probably around Australia somewhere then, my guess.

No rush for this tough, is a dev branch! just reporting something i wasn't sure should be working or not on weathermap.

Enjoy holidays!

**Comment by howardjones** [comment]
Auckland for the next few days and Sydney after :-) I'll expect I'll have
some downtime to have a first look at this though.

**Comment by ghie11** [comment]
hi.can you please help me how to configure the weather map plugin.
sorry this is my first time using cacti..

cacti-1.1.11
centos 7

thankyou

**Comment by howardjones** [comment]
@ghie11 please don't add support requests to existing tickets.

Sorry, there is currently no released version of weathermap that works with Cacti 1.x

**Comment by howardjones** [comment]
"Right now, he has his own permission system that does not recognize the Cacti Groups presently. " -> Uses the same system Cacti 0.8.8 has used for years. lol

I will work on something to make this compatible.
