### ISSUE TITLE
PAW theme breaks weathermap

### ISSUE THREAD

**Issue by imax64** [howardjones/network-weathermap#117]
using PAW theme, weathermap (latest 0.98a, CentOS 7.3, Cacti 1.1.24) tab only shows a blank page (no maps)
PHP console returns in error: complaining that treeView, listView and previewView are undefined. This performs flawless on classic theme.

i noticed that the problem resides in include/themes/paw/main.js (line 109, 110, 111):

>                                 +'<ul id="submenu-' + submenu_counter + '" class="submenuoptions" style="display:none;">'
>                                         +'<li><a href="'+urlPath+'graph_view.php?action=tree">'+treeView+'</a></li>'
>                                         +'<li><a href="'+urlPath+'graph_view.php?action=list">'+listView+'</a></li>'
>                                         +'<li><a href="'+urlPath+'graph_view.php?action=preview">'+previewView+'</a></li>'

if i comment them, it works just fine.

>                                 +'<ul id="submenu-' + submenu_counter + '" class="submenuoptions" style="display:none;">'
>                                         //+'<li><a href="'+urlPath+'graph_view.php?action=tree">'+treeView+'</a></li>'
>                                         //+'<li><a href="'+urlPath+'graph_view.php?action=list">'+listView+'</a></li>'
>                                         //+'<li><a href="'+urlPath+'graph_view.php?action=preview">'+previewView+'</a></li>'

**Comment by imax64** [comment]
sadly, you can no longer scroll vertically while in weathermaps after this workaround ...

**Comment by howardjones** [comment]
The cacti plugin is nowhere near complete...

**Comment by howardjones** [comment]
Closing this issue. Just tested current dev version with PAW theme, and this problem doesn't exist anymore. The plugin still isn't complete, but this problem is gone.
