### ISSUE TITLE
Blank page after adding a weathermap to display 

### ISSUE THREAD

**Issue by VictorJ76** [howardjones/network-weathermap#118]
Hi,
I Use cacti 0.8.8f with phpweathermap 0.98. I want to display my map and I have to add it via the page below :

`http://IP/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php

Everything works great until I add my map and Iand to this blank page
`http://IP/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap&file=simple.conf

In my logs I have this : 

`PHP Fatal error:  Uncaught Error: Call to undefined function mysql_real_escape_string() in /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php:837\nStack trace:\n#0 /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php(274): add_config('sup_hno.conf')\n#1 {main}\n  thrown in /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php on line 837, referer: http://IP/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker`

On my web browser, I get a 500 error.

**Comment by gadzet21** [comment]
Hi,
mysql_real_escape_string is not work in php7.
Please verify my modify weathermap 0.98 (attached) - cacti 0.8.8h.

[weathermap-modify-php7.zip](https://github.com/howardjones/network-weathermap/files/1495343/weathermap-modify-php7.zip)

Best regards
Jacek

**Comment by VictorJ76** [comment]
Thanks, that fix the issue, but I still have one to display my map as you can see to the screenshot. 
![capture](https://user-images.githubusercontent.com/18124387/33120952-d9cd7688-cf73-11e7-956f-b6ada9e9093f.PNG)

**Comment by VictorJ76** [comment]
It fixed, it was like the logs says, a permission problems.

**Comment by cortomalese** [comment]
Thank you, it works for me!
