### ISSUE TITLE
cacti 1.1.29

### ISSUE THREAD

**Issue by hellEVIL-13** [howardjones/network-weathermap#119]
2017/12/26 16:54:45 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
--
thrown in file: /usr/share/cacti/plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti-plugin-poller.php on line: 167
#1 /usr/share/cacti/lib/plugins.php(73):  api_plugin_run_plugin_hook('poller_bottom', 'weathermap',  'weathermap_poll...', Array)
#0 /usr/share/cacti/lib/plugins.php(170): weathermap_poller_bottom(Array)
2017/12/26 16:54:45 - ERROR PHP ERROR in  Plugin 'weathermap':  Uncaught Error: Call to undefined function weathermap_run_maps() in  /usr/share/cacti/plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti-plugin-poller.php:167

**Comment by netniV** [comment]
Which version of weathermap are you uisng?

**Comment by howardjones** [comment]
It doesn't make any difference which version really - there isn't a version that works with Cacti 1.1.29 (or 1.anything) currently.

**Comment by netniV** [comment]
I meant to ask for both cacti and weathermap to make sure it's 0.8.8 and 0.98 ;-)  But there will be a weathermap that works with Cacti 1.x soon..... sooon.... sooon ..... ;-)

**Comment by hellEVIL-13** [comment]
the latest version of the git

**Comment by netniV** [comment]
I would close this issue as a duplicate since it has been covered a lot on issue #120

**Comment by howardjones** [comment]
I'm going to close this one too (a) because the specific reported issue is resolved (the entire plugin is not functional, but _this_ issue is resolved) and (b) for same reason as #120:

> I don't really like using Issues for these long rambling threads of "things that don't currently work". The discussion is useful, but this isn't a great format for it, and the issue will basically never "really" close until the release version, by definition. This kind of thing works better in a [forum](http://forum.network-weathermap.com/), leaving Issues for one-time, clearly defined, and provably fixed issues.

**Comment by netniV** [comment]
Personally, there's isn't much difference to me.  I must prefer things like Slack for dev discussions but everyone's got their own view on how they like things :)

I'll post anything I find as a separate issue.
