### ISSUE TITLE
Cacti 1.1.33 plugin doesn't install

### ISSUE THREAD

**Issue by Izmenoff** [howardjones/network-weathermap#121]
![image](https://user-images.githubusercontent.com/17400240/35386616-be4cdd62-01dd-11e8-9653-7e12645f4b90.png)

25-Jan-2018 14:39:05 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
25-Jan-2018 14:39:05 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
25-Jan-2018 14:39:05 - ERROR PHP COMPILE_ERROR in Plugin 'weathermap': require_once(): Failed opening required '/usr/share/cacti/plugins/weathermap/lib/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in file: /usr/share/cacti/plugins/weathermap/lib/all.php on line: 12
25-Jan-2018 14:39:05 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 715 snmpagent_poller_bottom)(/lib/snmpagent.php: 457 snmpagent_get_pluginslist)(/lib/snmpagent.php: 542 include_once)(/plugins/weathermap/setup.php: 11 require_once)(/plugins/weathermap/setup10.php: 19 require_once)(/plugins/weathermap/lib/all.php: 12 require_once)(/plugins/weathermap/lib/all.php: 12 CactiErrorHandler)(/lib/functions.php: 4477 cacti_debug_backtrace)
25-Jan-2018 14:39:05 - ERROR PHP WARNING in Plugin 'weathermap': require_once(/usr/share/cacti/plugins/weathermap/lib/../vendor/autoload.php): failed to open stream: No such file or directory in file: /usr/share/cacti/plugins/weathermap/lib/all.php on line: 12
2018-01-25 14:39:02 - SPINE: Poller[1] ERROR: Spine Timed Out While Waiting for Threads to End

**Comment by howardjones** [comment]
Did you run `composer update` and `bower install` as it says in the README? autoload.php is generated by composer.

**Comment by netniV** [comment]
We need to update the error message handling in Cacti, that blank message/reason appears a few times because something is not matching the regex that cigamit was set initially.  If anything, it should have a generic message if all else fails.

**Comment by howardjones** [comment]
blank message? I see 4 lines of stacktrace that points right to the issue...

**Comment by netniV** [comment]
They come from the log file. I was referring to the screenshot. :)

**Comment by Izmenoff** [comment]
**howardjones** , Yes, i did, but
[root@srv-mncacti-p01 ~]# npm install bower -g
[..................] | normalizeTree: sill install loadCurrentTree
npm ERR! Linux 3.10.0-693.11.6.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "bower" "-g"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect
npm ERR! network connect ETIMEDOUT 151.101.112.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by howardjones** [comment]
OK, and I think composer probably failed too, because autoload.php doesn't exist.

Does this system have internet access?

**Comment by Izmenoff** [comment]
It hasn't internet access, only yum

**Comment by netniV** [comment]
It needs internet access to pull all its dependencies down and install them.

**Comment by netniV** [comment]
Also, please note that there is a patch https://github.com/Cacti/cacti/pull/1269 submitted to fix the blank messages on that dialog from cacti, so you should be able to see more of the error without resorting to the log files (though you should always check them on an error anyway).
