### ISSUE TITLE
Guzzle/Guzzle has now been replaced by GuzzleHttp/Guzzle

### ISSUE THREAD

**Issue by netniV** [howardjones/network-weathermap#123]
Everytime I run the composer update, it warns me about Guzzle/Guzzle being depreciated:
```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```
- Weathermap version: GitHub 3871ec0a08d393c318b447f7ea46e2f6d37163c3
- Host platform (OS version, PHP version, Cacti/Other NMS version): 
   - Ubuntu 16.04.3 (Xenial)
   - PHP 7.0.22-0ubuntu0.16.04.1
   - Cacti 1.1.34-dev

**Comment by howardjones** [comment]
The Code Climate test reporter (something used only during dev) requires a module which in turn requires guzzle/guzzle. It doesn't hurt anything, and doesn't affect the final weathermap at all.

It looks like the Code Climate module specifically depends on a very old version (1.0) of php-coveralls. This is resolved in the current (6.0!) version. Supposedly Code Climate will be deprecating this module altogether at some point, and actually, I am already using the newer version, so I'll take this dependency out of composer.json altogether.

Got there in the end.

```
# composer depends guzzle/guzzle
satooshi/php-coveralls  v1.1.0  requires  guzzle/guzzle (^2.8 || ^3.0)
# composer depends satooshi/php-coveralls
codeclimate/php-test-reporter  v0.4.4  requires  satooshi/php-coveralls (^1.0)
```
