### ISSUE TITLE
Titles of management table are in German

### ISSUE THREAD

**Issue by netniV** [howardjones/network-weathermap#124]
I know it's still work in progress, but thought you might have missed this part.  The titles of the table on the cacti plugin management page (weathermap-cacti10-plugin-mgmt.php) are in German:
![image](https://user-images.githubusercontent.com/9052188/35575347-11bead5a-05d4-11e8-8425-0851879ab7a7.png)

**Comment by howardjones** [comment]
It's French, not German :-) Testing internationalisation support in React, so there can be translations. Don't worry, it won't be the default.

**Comment by netniV** [comment]
Well, my bad for not noticing the difference lol 👍 🥇

**Comment by howardjones** [comment]
Now reflects your Cacti language setting (as long as you speak english or french - that's the only one I added to prove that it works)
