### ISSUE TITLE
Docs folder gives permission denied

### ISSUE THREAD

**Issue by netniV** [howardjones/network-weathermap#125]
```
Forbidden
You don't have permission to access /plugins/weathermap/docs/ on this server.
```
This is the error received when attempting to click the Docs link on the plugin tab.  Again, I know this is WIP just thought you might like a record of the issue.

**Comment by howardjones** [comment]
That's interesting. Does the directory exist? It should do. Actually, is your Cacti install in the web root?

**Comment by netniV** [comment]
I was about to say "_Nope, it's in it's own folder as I have multiple Cacti's :)_" when I realised that yes it is.  It's got it's own URL and the config.php reflects that:
```
$url_path = '/';
```
This may be an issue where only index.php is defined as a default document? When I browse to the index.html that works.

**Comment by howardjones** [comment]
Yes, I think it must be something like that. I guess I'll update the URL to include the filename. Bit messier, but will always work.
