### ISSUE TITLE
Can not editor my map！

### ISSUE THREAD

**Issue by canghai908** [howardjones/network-weathermap#13]
![12](https://cloud.githubusercontent.com/assets/1450994/5760387/26e9009e-9d0f-11e4-91e8-0053e1fdc182.jpg)
my map config is

# Automatically generated by php-weathermap v0.97c

FONTDEFINE 100 /var/www/html/plugins/weathermap/msyh.ttf 10

WIDTH 1024
HEIGHT 768
HTMLSTYLE overlib
KEYFONT 100
TITLE test
TIMEPOS 746 17 Created: %b %d %Y %H:%M:%S

KEYPOS DEFAULT 823 491 Traffic Load
KEYTEXTCOLOR 0 0 0
KEYOUTLINECOLOR 0 0 0
KEYBGCOLOR 255 255 255
BGCOLOR 255 255 255
TITLECOLOR 0 0 0
TIMECOLOR 0 0 0
SCALE DEFAULT 0    0    192 192 192  
SCALE DEFAULT 0    1    255 255 255  
SCALE DEFAULT 1    10   140   0 255  
SCALE DEFAULT 10   25    32  32 255  
SCALE DEFAULT 25   40     0 192 255  
SCALE DEFAULT 40   55     0 240   0  
SCALE DEFAULT 55   70   240 240   0  
SCALE DEFAULT 70   85   255 192   0  
SCALE DEFAULT 85   100  255   0   0  

SET nowarn_clipping 1

# End of global section

# TEMPLATE-only NODEs:
NODE DEFAULT
	LABELFONT 100
	MAXVALUE 100

# TEMPLATE-only LINKs:
LINK DEFAULT
	WIDTH 2
	BWFONT 100
	COMMENTFONT 100
	BWLABEL bits
	BANDWIDTH 100M

# regular NODEs:
NODE 互联网交换机01
	LABEL 互联网交换机01
	INFOURL /graph.php?rra_id=all&local_graph_id=11
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=11
	POSITION 802 370

NODE 互联网交换机02
	LABEL 互联网交换机02
	INFOURL /graph.php?rra_id=all&local_graph_id=17
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=17
	POSITION 953 370

NODE node08151
	LABEL Node
	INFOURL /graph.php?rra_id=all&local_graph_id=39
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=39
	POSITION 800 174

NODE 电信网
	LABEL 电信网
	ICON images/Cloud-Filled.png
	POSITION 802 66

NODE node05202
	LABEL Node
	POSITION 955 177

NODE 联通网
	LABEL 联通网
	ICON images/Cloud-Filled.png
	POSITION 953 66

NODE 内层防火墙01
	LABEL 内层防火墙01
	POSITION 470 210

NODE 内层防火墙02
	LABEL 内层防火墙02
	POSITION 621 210

NODE 核心路由器02
	LABEL 核心路由器02
	POSITION 621 54

NODE 核心路由器01
	LABEL 核心路由器01
	POSITION 470 54

NODE 核心交换机01
	LABEL 核心交换机01
	POSITION 470 370

NODE 核心交换机02
	LABEL 核心交换机02
	POSITION 621 370

NODE 数据库服务器A
	LABEL 数据库服务器A
	INFOURL /graph.php?rra_id=all&local_graph_id=124
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=124
	POSITION 427 442

NODE 数据库服务器B
	LABEL 数据库服务器B
	INFOURL /graph.php?rra_id=all&local_graph_id=151
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=151
	POSITION 621 444

NODE 内网汇聚01
	LABEL 内网汇聚01
	POSITION 108 370

NODE 内网汇聚02
	LABEL 内网汇聚02
	POSITION 297 370

# regular LINKs:
LINK node1-node2
	INFOURL /graph.php?rra_id=all&local_graph_id=16
	OVERLIBGRAPH /graph_image.php?local_graph_id=16&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/sw01_traffic_in_19.rrd
	NODES 互联网交换机02 互联网交换机01

LINK node08151-互联网交换机01
	INFOURL /graph.php?rra_id=all&local_graph_id=39
	OVERLIBGRAPH /graph_image.php?local_graph_id=39&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/f5-01_traffic_in_42.rrd
	NODES node08151 互联网交换机01

LINK 电信网-node08151
	NODES 电信网 node08151

LINK 联通网-node05202
	NODES 联通网 node05202

LINK 联通网-node05202a
	NODES 联通网 node05202

LINK 联通网-node05202aa
	NODES 联通网 node05202

LINK node05202-互联网交换机02
	NODES node05202 互联网交换机02

LINK node08585-node08590
	NODES 内层防火墙02 核心交换机02

LINK node08585-node08580
	NODES 内层防火墙02 内层防火墙01

LINK node08588-node08580
	INFOURL /graph.php?rra_id=all&local_graph_id=83
	OVERLIBGRAPH /graph_image.php?local_graph_id=83&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/01_traffic_in_86.rrd
	NODES 核心交换机01 内层防火墙01

LINK node08588-node08590
	NODES 核心交换机01 核心交换机02

LINK 核心路由器01-内层防火墙01
	INFOURL /graph.php?rra_id=all&local_graph_id=46
	OVERLIBGRAPH /graph_image.php?local_graph_id=46&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/01_traffic_in_49.rrd
	NODES 核心路由器01 内层防火墙01

LINK 内层防火墙02-核心路由器02
	INFOURL /graph.php?rra_id=all&local_graph_id=57
	OVERLIBGRAPH /graph_image.php?local_graph_id=57&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/02_traffic_in_60.rrd
	NODES 内层防火墙02 核心路由器02

LINK 互联网交换机01-内层防火墙01
	INFOURL /graph.php?rra_id=all&local_graph_id=16
	OVERLIBGRAPH /graph_image.php?local_graph_id=16&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/sw01_traffic_in_19.rrd
	NODES 互联网交换机01 内层防火墙01

LINK 内层防火墙02-互联网交换机02
	INFOURL /graph.php?rra_id=all&local_graph_id=20
	OVERLIBGRAPH /graph_image.php?local_graph_id=20&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/sw02_traffic_in_23.rrd
	NODES 内层防火墙02 互联网交换机02

LINK 核心路由器01-核心路由器02
	INFOURL /graph.php?rra_id=all&local_graph_id=53
	OVERLIBGRAPH /graph_image.php?local_graph_id=53&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/01_traffic_in_56.rrd
	NODES 核心路由器01 核心路由器02

LINK 内层防火墙01-内网汇聚01
	NODES 内层防火墙01 内网汇聚01

LINK 内层防火墙02-内网汇聚02
	NODES 内层防火墙02 内网汇聚02

# That's All Folks!

when I editor the map，the map can‘t editor！Like this！
![12](https://cloud.githubusercontent.com/assets/1450994/5760387/26e9009e-9d0f-11e4-91e8-0053e1fdc182.jpg)

**Comment by howardjones** [comment]
What does it say in the httpd error log? Usually this is the result of a php error.

**Comment by canghai908** [comment]
I solved！I found the error on http errors log.
```bash
[root@localhost ~]# tail -f /var/log/httpd/error_log
[Sun Jan 18 04:02:05 2015] [notice] Apache/2.2.3 (Red Hat) configured -- resuming normal operations
[Sun Jan 18 14:38:53 2015] [error] [client 10.10.241.12] PHP Fatal error:  Allowed memory size of 16777216 bytes exhausted (tried to allocate 3072 bytes) in /var/www/html/plugins/weathermap/lib/Weathermap.class.php on line 3301, referer: http://10.10.249.247/plugins/weathermap/editor.php?mapname=hbdzka.conf&plug=
[Sun Jan 18 14:39:14 2015] [error] [client 10.10.241.12] PHP Fatal error:  Allowed memory size of 16777216 bytes exhausted (tried to allocate 3072 bytes) in /var/www/html/plugins/weathermap/lib/Weathermap.class.php on line 3301, referer: http://10.10.249.247/plugins/weathermap/editor.php?mapname=hbdzka.conf&plug=
[Sun Jan 18 14:40:41 2015] [error] [client 10.10.241.12] PHP Fatal error:  Allowed memory size of 16777216 bytes exhausted (tried to allocate 3072 bytes) in /var/www/html/plugins/weathermap/lib/Weathermap.class.php on line 3301, referer: http://10.10.249.247/plugins/weathermap/editor.php?mapname=hbdzka.conf&plug=
[Sun Jan 18 14:40:46 2015] [error] [client 10.10.241.12] PHP Fatal error:  Allowed memory size of 16777216 bytes exhausted (tried to allocate 3072 bytes) in /var/www/html/plugins/weathermap/lib/Weathermap.class.php on line 3301, referer: http://10.10.249.247/plugins/weathermap/editor.php?mapname=hbdzka.conf&plug=
```
So. I edit php.ini and increate the memory.Restart httpd server, It works ok! Thank you!
```bash
memory_limit = 512M  
```

**Comment by howardjones** [comment]
Cool! Glad it is working :-)
