### ISSUE TITLE
How to add weathermaps - management shows blank

### ISSUE THREAD

**Issue by MrDibbley** [howardjones/network-weathermap#131]
New install of 1.1.34 with latest commit of weathermap. Under management none of the sample maps show up and seems to be no way to add them see screenshot 

<a href="https://ibb.co/mF56wS"><img src="https://preview.ibb.co/d9yRwS/Capture.jpg" alt="Capture" border="0"></a>

I have run both bower install and composer update with no errors

Thanks

**Comment by netniV** [comment]
Technically, Weathermaps is still in development for 1.x of cacti.  There is also a weathermaps tab which has an editor link in it.  But most functionality is basic at the moment.  @howardjones is still actively working on it though so hopefully not much longer before he's fully ready.  

If you have git clone'd the source, it should be simple to keep up with the dev process via a git pull.
