### ISSUE TITLE
Unable to install 1.0.0dev  on Cacti 1.1.28

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#132]
My understanding that Howie is close to  1.0.0dev release, so I decided to install it on top of my very 8 month old buggy version.  Unfortunately I was unable to get out of the gate,
WHen I go into plugins to install the the new 1.0.0dev release, it doesn't install and I get error msgs in log below:
Please assist I am looking forward to participate in beta testing as I am a heavy user :)

2018/02/19 17:02:48 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2018/02/19 17:02:48 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4446 cacti_debug_backtrace)
2018/02/19 17:02:48 - ERROR PHP COMPILE_ERROR in Plugin 'weathermap': require_once(): Failed opening required '/var/www/html/plugins/weathermap/lib/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in file: /var/www/html/plugins/weathermap/lib/all.php on line: 12
2018/02/19 17:02:48 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 715 snmpagent_poller_bottom)(/lib/snmpagent.php: 457 snmpagent_get_pluginslist)(/lib/snmpagent.php: 542 include_once)(/plugins/weathermap/setup.php: 11 require_once)(/plugins/weathermap/setup10.php: 19 require_once)(/plugins/weathermap/lib/all.php: 12 require_once)(/plugins/weathermap/lib/all.php: 12 CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)
2018/02/19 17:02:48 - ERROR PHP WARNING in Plugin 'weathermap': require_once(/var/www/html/plugins/weathermap/lib/../vendor/autoload.php): failed to open stream: No such file or directory in file: /var/www/html/plugins/weathermap/lib/all.php on line: 12 

![errors](https://user-images.githubusercontent.com/11211789/36399284-31c7100e-1599-11e8-8763-07f671d9d560.jpg)

**Comment by howardjones** [comment]
Read the readme. Run composer and bower.

autoload.php is created by composer.

This won't be necessary in the release version.

Also, I'm not that close - the management UI is not really there yet.

**Comment by netniV** [comment]
Aww, I thought you were further along, I've been bigging you up 👍

**Comment by ikorzha** [comment]
netniV, Yes you were, I gathered Howie's progress info based on your comments that I am subscribed to :)
Thank you Howie for your comments, I will read readme.

**Comment by howardjones** [comment]
I should add that I'm hoping it will make quick progress - the guts (that update the database etc) are already there, just no user interface. There are a few parts that I don't know yet how they will work though! (map cycling and overlib, at least)
