### ISSUE TITLE
Cacti Plugin is creating duplicate records in plugin_realms

### ISSUE THREAD

**Issue by netniV** [howardjones/network-weathermap#133]
Hey @howardjones,

For some reason, your plugin is creating many plugin_realm entries.  I am not sure if this is a bug with the cacti realm code or your method of creating the realm but if you select the plugini_realm table, it has a few copies of your plugin within it.

```sql
select * from plugin_realms
```

![image](https://user-images.githubusercontent.com/9052188/36528814-4ccb7a2c-17ae-11e8-8afd-3c3235c56cc8.png)

As per https://github.com/Cacti/cacti/issues/1388

**Comment by pautiina** [comment]
![image](https://user-images.githubusercontent.com/11805503/36529081-eee65b18-17bf-11e8-96ff-d3c35eca9d9b.png)

**Comment by netniV** [comment]
I think this may be, because the call to api_plugin_register_realm is occurring often to make sure it's registered.

**Comment by netniV** [comment]
Confirmed, bug with api_plugin_register_realm() introduce to develop code.  The check to create the realm had become inverted somehow.

**Comment by netniV** [comment]
Actually, I'm going to reopen this as my logs are being spammed.  I added a simple cacti_log() to see when the plugin realms function was being called, I then went to the site logged in an enabled quicktree....

```
2018/02/22 09:27:09 - CMDPHP api_plugin_register_realm('quicktree', 'quicktree.php', 'Plugin -> QuickTree: Access', 1)
--
2018/02/22 09:27:09 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:27:09 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:27:09 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:27:08 - CMDPHP api_plugin_register_realm('quicktree', 'quicktree.php', 'Plugin -> QuickTree: Access', 1)
2018/02/22 09:27:08 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:27:08 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:27:08 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:27:07 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:27:07 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:27:07 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:26:59 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:26:59 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:26:59 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:26:56 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:26:56 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:26:56 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:26:56 - AUTH LOGIN: User 'admin' Authenticated
2018/02/22 09:26:56 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:26:56 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:26:56 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:26:51 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:26:51 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:26:51 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:25:03 - THOLDLISTS STATS: Time:0.01 Imports:1 Imported:0
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-editor.php', 'Weathermap: Edit Maps', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin-mgmt.php', 'Weathermap: Configure/Manage', 1)
2018/02/22 09:25:03 - CMDPHP api_plugin_register_realm('weathermap', 'weathermap-cacti10-plugin.php', 'Weathermap: View', 1)
```

As you can see, before I even went to login I've been spammed with realm creations (presumably by the poller).

**Comment by howardjones** [comment]
If ever there was a place for a composite database key...

I don't get this on my local Cacti 1.1.29 install, incidentally.

**Comment by netniV** [comment]
The duplication of realm is a cacti_bug, but interesting to know it's only a dev thing for the repeated plugin_realm call.  The thing is there is also a change now to realm_register where it will automatically assign the current user as having permission... so that change will have an impact here too.

**Comment by howardjones** [comment]
The database will stop the duplicates for you with a properly defined composite key, regardless of what check is done in the php code.

I don't really see why automatically adding the current user has any particular impact, once the bug is fixed.

**Comment by netniV** [comment]
I'd have to check what happens with realms if the plugin exists but is not installed yet.  I think somewhere the files still get included... thus if you have the dev version and it's registering the realm, the first person who hits the register_realm will be the one to get permission.

Thus, it may be a NON admin that does if it's not just done via the install code.  Something to check and be aware of more than suggesting it's completely wrong.

**Comment by howardjones** [comment]
OK, I see what you mean. I can move it to the place where the hooks are registered easily enough.

**Comment by howardjones** [comment]
So I just checked, and *actuallly*, the `api_plugin_register_realm` calls are in the  `config_arrays` hook (because they used to updating Cacti arrays). That shouldn't be called for a non-installed plugin. 

Anyway, I've moved them in next to the hook registration function calls.

**Comment by netniV** [comment]
Hmm, another thing to test out. I still think plugin code gets called somewhere in the base before it's installed. Your change should at least reduce the DB hit even though it was minor lol.

**Comment by howardjones** [comment]
It definitely did in early 1.x versions, because I could break the Cacti installer just by having code in the plugins directory. That should never happen.

**Comment by howardjones** [comment]
Unit tests. The more you can test automatically, the less stuff like this slips through.

**Comment by netniV** [comment]
Totally agree.  Problem is, most of cacti is still based loosely around the 0.8.8 code... which means in page functions!  The API though, yeah should have unit tests.

**Comment by howardjones** [comment]
Definitely recommend this talk... I only found it recently, but it's essentially what I've been through with Weathermap over the last couple of years, and a couple of work projects, to varying degrees (just getting to the DI stuff now)

https://leanpub.com/mlaphp

**Comment by netniV** [comment]
https://github.com/Cacti/cacti/issues/1389
