### ISSUE TITLE
Autoload.php not found

### ISSUE THREAD

**Issue by gebster** [howardjones/network-weathermap#134]
New install of Cacti 1.1.36 and Weathermap.  I got Weathermap from github.
git clone https://github.com/howardjones/network-weathermap/ 

When trying to install I get the following errors.

03/01/2018 14:03:13 - ERROR PHP WARNING in  Plugin 'weathermap': require_once(/var/www/html/cacti/plugins/weathermap/lib/../vendor/autoload.php): failed to open stream: No such file or directory in file: /var/www/html/cacti/plugins/weathermap/lib/all.php  on line: 12
03/01/2018 14:03:13 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins.php: 74 api_plugin_install)(/lib/plugins.php: 479 include_once)(/plugins/weathermap/setup.php: 11 require_once)(/plugins/weathermap/setup10.php: 19 require_once)(/plugins/weathermap/lib/all.php: 12 require_once)(/plugins/weathermap/lib/all.php: 12 CactiErrorHandler)(/lib/functions.php: 4586 cacti_debug_backtrace)
03/01/2018 14:03:13 - ERROR PHP COMPILE_ERROR in  Plugin 'weathermap': require_once(): Failed opening required '/var/www/html/cacti/plugins/weathermap/lib/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in file: /var/www/html/cacti/plugins/weathermap/lib/all.php on line: 12
03/01/2018 14:03:13 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4629 cacti_debug_backtrace)
03/01/2018 14:03:13 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'

When looking at the directories the vendor one does not exist.

**Comment by laf** [comment]
Did you run `bower install` and `composer update` as per the docs?

**Comment by bsyd** [comment]
same error here.
Did all steps.
yum install -y nodejs composer
bower install
composer update

[Fri Mar 02 13:59:27.846062 2018] [:error] [pid 21577] [client 192.168.10.39:51516] PHP Fatal error:  require_once(): Failed opening required '/usr/share/cacti/plugins/weathermap/lib/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/cacti/plugins/weathermap/lib/all.php on line 12, referer: http://cacti/cacti/plugins.php

# ls -l vendor/
total 0
drwxr-xr-x 5 root root 137 Mar  2 13:58 jquery
drwxr-xr-x 2 root root 151 Mar  2 13:58 jquery-fastlivefilter
drwxr-xr-x 6 root root 300 Mar  2 13:58 jquery-idletimer

cacti-1.1.36-1.el7.noarch
php-5.4.16-43.el7_4.x86_64

**Comment by bsyd** [comment]
Oh, I see another error during composer update : 
`# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.7.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.9 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.8 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.7 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.6 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.5 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.4 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.3 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.27 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.26 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.25 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.24 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.23 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.22 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.21 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.20 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.2 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.19 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.18 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.17 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.16 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.15 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.14 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.13 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.12 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.11 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.10 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.1 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.7.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.8 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.7 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.6 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.5 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.4 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.3 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.2 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.1 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.6.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.7 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.6 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.5 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.4 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.3 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.2 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.1 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.5.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.8 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.7 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.6 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.5 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.4 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.3 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.2 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.1 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.5 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.4 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.3 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.2 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.1 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.3.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.9 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.8 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.7 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.6 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.5 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.4 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.3 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.2 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.12 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.11 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.10 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.1 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.2.0 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.x-dev requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.7 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.6 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.5 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.4 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.3 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.2 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.1 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.1.0 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.x-dev requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.9 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.8 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.7 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.6 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.5 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.4 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.3 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.2 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.10 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.1 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - phpunit/phpunit 5.0.0 requires php >=5.6 -> your PHP version (5.4.16) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ~5 -> satisfiable by phpunit/phpunit[5.0.0, 5.0.1, 5.0.10, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.0.x-dev, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.x-dev, 5.2.0, 5.2.1, 5.2.10, 5.2.11, 5.2.12, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9, 5.2.x-dev, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.3.x-dev, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.7, 5.4.8, 5.4.x-dev, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 5.5.7, 5.5.x-dev, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.6.x-dev, 5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.27, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev].
`

**Comment by netniV** [comment]
Basically, that means there is a minimum requirement of 5.6 for the library component PHPUnit used by Weathermaps, as opposed to the 5.4 for base cacti.

**Comment by bsyd** [comment]
I see.  Upgrading PHP to 7.2.3 and run composer install again.
Much better.  dependencies installed and autoload.php present.

You should set a minimum requirement for php5.6 on the main page.

**Comment by bsyd** [comment]
I got another unrelated error.  But for me it's ok with this one.
Letting the original poster decide to close or not.

**Comment by howardjones** [comment]
You can avoid a lot of the composer dependencies if you are not intending to contribute code.
`composer update --no-dev`  will dramatically reduce the number of dependencies, and especially ones that want current php like phpunit.

But also, in `CHANGES`: "BREAKING CHANGES: Weathermap now makes use of PHP 5.6 features,". I will try to make the change to composer.json to reflect this too. And probably something to explicitly check for vendor/autoload.php and tell you to read the README :-)

**Comment by bsyd** [comment]
I saw no mention of any PHP version in the README...
A "minimum requirements" section would be nice.

**Comment by netniV** [comment]
Given the above, I would suggest telling them to read the CHANGES and README @howardjones  ;-)

**Comment by howardjones** [comment]
For the release version, there's a box on the page with the download link. I will update both.

**Comment by gebster** [comment]
Thanks guys, I got the bower installed correctly after a few php5 package installs.

apt-get php5-sqlite3
apt-get install php5-sqlite
apt-get install php5-xsl

Did have a Duplicate column name  error right after but other the night time it must of cleared itself.

03/01/2018 15:58:26 - ERROR PHP ERROR in  Plugin 'weathermap': Uncaught exception 'PDOException' with message 'SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'usergroupid'' in /var/www/html/cacti/plugins/weathermap/lib/Weathermap/Integrations/MapManager.php:788
Stack trace:
#0 /var/www/html/cacti/plugins/weathermap/lib/Weathermap/Integrations/MapManager.php(788): PDO->query('ALTER TABLE wea...')
#1 /var/www/html/cacti/plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti10-plugin-hooks.php(15): Weathermap\Integrations\MapManager->initializeDatabase()
#2 /var/www/html/cacti/plugins/weathermap/setup10.php(58): weathermap_setup_table()
#3 /var/www/html/cacti/lib/plugins.php(530): plugin_weathermap_install()
#4 /var/www/html/cacti/plugins.php(74): api_plugin_install('weathermap')
#5 {main}
  thrown in file: /var/www/html/cacti/plugins/weathermap/lib/Weathermap/Integrations/MapManager.php on line: 788
03/01/2018 15:58:26 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4629 cacti_debug_backtrace)
03/01/2018 15:58:26 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
03/02/2018 08:29:31 - AUTH LOGIN: User 'admin' Authenticated via Authentication Cookie


Thing morning I was able to into.
