### ISSUE TITLE
Duplicate column name 'usergroupid'

### ISSUE THREAD

**Issue by bsyd** [howardjones/network-weathermap#135]
on a CentOS 7 machine :
Software Versions : 
cacti-1.1.36-1.el7.noarch
php-7.2.3-2.el7.remi.x86_64
composer-1.6.3-1.el7.noarch
nodejs-6.12.3-1.el7.x86_64
MariaDB-server-10.1.31-1.el7.centos.x86_64

plugin installed with `git clone`  in /usr/share/cacti/plugins/weathermap (last commit : 376bee569862a1455dbb94b11d57f22e3bd586b4 )
bower install && composer update with no errors

going to /cacti/plugins.php and choosing the install link gives this error in apache logs : 
`[Fri Mar 02 14:20:43.694968 2018] [php7:error] [pid 25691] [client 192.168.10.39:51983] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'usergroupid' in /usr/share/cacti/plugins/weathermap/lib/Weathermap/Integrations/MapManager.php:788\nStack trace:\n#0 /usr/share/cacti/plugins/weathermap/lib/Weathermap/Integrations/MapManager.php(788): PDO->query('ALTER TABLE wea...')\n#1 /usr/share/cacti/plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti10-plugin-hooks.php(15): Weathermap\\Integrations\\MapManager->initializeDatabase()\n#2 /usr/share/cacti/plugins/weathermap/setup10.php(58): weathermap_setup_table()\n#3 /usr/share/cacti/lib/plugins.php(530): plugin_weathermap_install()\n#4 /usr/share/cacti/plugins.php(74): api_plugin_install('weathermap')\n#5 {main}\n  thrown in /usr/share/cacti/plugins/weathermap/lib/Weathermap/Integrations/MapManager.php on line 788, referer: http://cactihp/cacti/plugins.php
`

**Comment by howardjones** [comment]
Thanks! I think this one is sorted now (worked on my test 1.1.29 install, at least)

**Comment by bsyd** [comment]
confirmed.
