### ISSUE TITLE
Editor - Create Map

### ISSUE THREAD

**Issue by netniV** [howardjones/network-weathermap#137]
When using Editor - Create Map (weathermap-cacti10-plugin-editor.php?mapname=Mark&action=newmap&plug=)

```
VALIDATION FAIL
```

I know you said the Create Map screen was a dummy screen but I saw this one in the editor and tried it.

**Comment by howardjones** [comment]
That's supposed to have a 1 on the end of the URL. I'm pretty sure that's what the validation error is for. That's a bug :-)

Although the filename should have a .conf on the end, too.

**Comment by netniV** [comment]
That's a good start for when your working on the screen then 💃

**Comment by howardjones** [comment]
OK. plug has the correct value (wasn't passed through). The editor already adds .conf onto the end if there isn't one, but then failed its own validation for that. Fixed that too. Push shortly.
