### ISSUE TITLE
Error 500 - Hitting return in Title (debug section)

### ISSUE THREAD

**Issue by netniV** [howardjones/network-weathermap#138]
PHP Fatal error:  Uncaught Weathermap\\Core\\WeathermapInternalFail: Don't like this config filename in /usr/share/cacti/site/plugins/weathermap/lib/Weathermap/Editor/EditorUI.php:972
Stack trace:
```
#0 /usr/share/cacti/site/plugins/weathermap/editor.php(38): Weathermap\\Editor\\EditorUI->main(Array, Array, true)
#1 /usr/share/cacti/site/plugins/weathermap/weathermap-cacti10-plugin-editor.php(26): require_once('/usr/share/cact...')
#2 {main}
thrown in /usr/share/cacti/site/plugins/weathermap/lib/Weathermap/Editor/EditorUI.php on line 972, 
referer: weathermap/weathermap-cacti10-plugin-editor.php?mapname=empty.conf&action=nothing&plug=1
```

**Comment by howardjones** [comment]
Can you explain a bit more? Hitting return in title?

empty.conf is a valid filename... does the file exist?

**Comment by netniV** [comment]
Yeah, I did what you suggested, touched the file.  In the debug section at the bottom (which I maybe shouldn't be messing with) I just happened to click with the mouse.  Then I hit return. Then I got the error.

**Comment by howardjones** [comment]
The fix for this will be to remove the debug section :-) Basically it allows you to submit commands to the editor, with any (or no) action. The editor validates input, sees action is blank and gets upset. Correctly, but not really helpful. So I'll hide those before the final.

**Comment by netniV** [comment]
Isn't this technically fixed now then?
