### ISSUE TITLE
Error message: 500 Internal Server Error when activating networkweather plugin

### ISSUE THREAD

**Issue by akbarabdullah1989** [howardjones/network-weathermap#140]
When the networkweather plugin is enabled the message appears :

Action failed
Sorry, we could not process your last action.
Error:  500 Internal Server Error
Reason:  The response to the last action was unexpected.

Installed on cacti 1.1.37

**Comment by gebster** [comment]
You'll get this message if bower is not installed.

**Comment by howardjones** [comment]
Would you? I don't see why missing javascript would cause a server-side error...

Logs will shed some light either way, though.

**Comment by akbarabdullah1989** [comment]
how to install bower, I've been looking for reference install bower on weathermap plugin but still error

**Comment by akbarabdullah1989** [comment]
I use php72

**Comment by howardjones** [comment]
1) Please read the README - that explains how to install bower.
2) Please look in your httpd error.log. An http 500 error should produce some log entries in there.

**Comment by akbarabdullah1989** [comment]
like this error on the apache log :
" [Thu Apr 05 04:24:06.372399 2018] [php7:error] [pid 1399] [client 192.168.1.1:37936] PHP Fatal error:  Uncaught Exception: No autoloader present. Did you read README.md for dev-specific instructions? in /var/www/html/cacti/plugins/weathermap/lib/all.php:15\nStack trace:
\n#0/var/www/html/cacti/plugins/weathermap/setup10.php(19): require_once()\n#1 /var/www/html/cacti/plugins/weathermap/setup.php(11): require_once('/var/www/html/c...')
\n#2 /var/www/html/cacti/lib/plugins.php(479): include_once('/var/www/html/c...')
\n#3 /var/www/html/cacti/plugins.php(74): api_plugin_install('weathermap')\n#4 {main}\n  thrown in /var/www/html/cacti/plugins/weathermap/lib/all.php on line 15, referer: http://192.168.1.2/cacti/plugins.php "

from the description seen that php fatal error

**Comment by howardjones** [comment]
OK, so actually it's the `composer` part of the README that causes the error. Same resolution though: read the README! :-)

**Comment by netniV** [comment]
You could probably put some error handling around that and then display a message that says "READ THE README!!!"

**Comment by howardjones** [comment]
You mean this? lol 
![image](https://user-images.githubusercontent.com/912421/38366798-d455290c-38d8-11e8-8423-263e05e25ec4.png)

and this?

![image](https://user-images.githubusercontent.com/912421/38366843-f3e764d8-38d8-11e8-988c-9caa6373a9d6.png)

Unless there's a way for an exception to show up a message in the Cacti UI, I don't think I can do more.

**Comment by netniV** [comment]
Yeah but I more meant, prevent the 500 in the first place with an even larger version such as:

<hr>

### Error 500 - You didn't did you?

<hr>

How many times did I tell you to read the README.... 

Here:
![](https://user-images.githubusercontent.com/912421/38366798-d455290c-38d8-11e8-8423-263e05e25ec4.png)

And Here:
![](https://user-images.githubusercontent.com/912421/38366843-f3e764d8-38d8-11e8-988c-9caa6373a9d6.png)

**Comment by howardjones** [comment]
Is there a way for that message to actually appear on screen in Cacti? As far as I know it will just silently disable the plugin, and we are back to the same situation, only even quieter.

**Comment by howardjones** [comment]
I did consider having it actually disabled out of the box, with a specific instruction to enable it in the README, but that seems a bit obnoxious. I did that with the 'recalculate now' button in the end, because so many people who didn't understand the file permissions would use it. You had to set a variable to true in the code: `$i_have_read_the_manual_and_understand_the_permissions_issues=TRUE` :-)

**Comment by netniV** [comment]
Cacti now only disables on unhandled errors.  If you use the @ symbol in front of the autoloader, this should allow you to try and create the object.  If it's null, you know that it does not exist.  Alternatively, if you have installed your own error handler, you can then catch the error, handle it and display your own message.
