### ISSUE TITLE
Problems with UI

### ISSUE THREAD

**Issue by pr1zrakkk** [howardjones/network-weathermap#142]
**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use Github issues to report bugs or add specific development tasks_

For feature requests, support issues ("how do I....?") or discussion, please
use the forum at https://forum.network-weathermap.com/

FOR BUGS:

Describe the problem and include the following information:

- Something more like "I tried to X by doing Y but instead, Z happened." and *not* "I can't X"
- Weathermap version
- Host platform (OS version, PHP version, Cacti/Other NMS version)
- Any error message you got, including:

  - Errors in httpd error_log
  - Warnings in cacti.log (or equivalent)
  - Any error messages in the browser javascript console, for editor/web issues (e.g. press F12 in Chrome)

**Comment by howardjones** [comment]
That's correct, it's not finished.

**Comment by FredNeuberger** [comment]
Hey there, do you have a rough idea on how/when you will proceed?

Did you ever think of some sort of crowdfunding for this project?

**Comment by howardjones** [comment]
How: yes. When: not as much - it's moving forward slowly, but depends on what else is going on with my family etc.

I don't see what crowdfunding would achieve. It's not an issue of money, but time.

**Comment by netniV** [comment]
I think people ask that more to be able to pay back for the awesome product you produce (when it's working properly) ;-)

**Comment by howardjones** [comment]
Touché :-)

At the moment, I guess I see it as a way for people to be "owed" - once this version is *done* maybe it could be revisited!

**Comment by vRobM** [comment]
Perhaps you need a bounty program to distribute the time sharing on these
feature issues?

++ Rob

About me <https://remote.com/r>

**Comment by howardjones** [comment]
I think that for 1.1, that could definitely work. In this particular instance, I'm having enough trouble getting it straight in my head, let alone managing it for a team :-)

**Comment by demokom-gmail-com** [comment]
Hello, Howard
My question is simple, so I will write here.
I have Ubuntu 16.04, cacti 1.1.38, last Weathermap plugin 1.0 from github.
All works well, except that new maps do not appear in the map list. As far as I understand, it's enough to add an entry about these maps to the mysql table and they will be available.
Please publish a sample of sql script to create this entry.
Thanks.

**Comment by zdzo** [comment]
Hello howard
I have the same problem with the "Button not working (Create MapAdd MapAdd GroupSettings) " can you tell how to add from cli to the wheathermap web interface to access from the web ( i mean to make link/icon of created map in the web (wheathermap) intaface tab )

**Comment by howardjones** [comment]
There isn't a CLI for weathermap.

**Comment by ika777** [comment]
hello, 
   i added plugin V1.0 in cacti V1.1.38 

     i have created map.conf file from Weathermap editor, but there is no option to add map in main Weathermap page. is there any option to do this ?

         thanks,

**Comment by netniV** [comment]
Weathermaps 1.0 isn't finished yet.  There are still some bits of functionality missing.
