### ISSUE TITLE
assert() funtion is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by edwardhu** [howardjones/network-weathermap#144]
Sir, I try to open the editor but failed.
Here are my working environment and error msgs.
For your reference, thank you. :)
- Weathermap 1.0 dev
- Host platform (Win 7 x64, PHP 7.2, Cacti 1.1.38)
- Error Messages:

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\MapDataItem.php on line 141

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\MapDataItem.php on line 141

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 215

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 216

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 217

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 218

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 345

**Comment by netniV** [comment]
I've submitted a patch to correct the issue, though Howie may decide to just comment out those assertions instead or even change the assertion if he believes it to be wrong.
