### ISSUE TITLE
Editor Weathermap

### ISSUE THREAD

**Issue by infovinicius** [howardjones/network-weathermap#149]
Hi Guys,

I followed all the steps but I was confused in the fifth step because the described option "**please note when you create a MAP, please click Map Style, ensure Overlib is selected for HTML Style and click submit. Also, ensure you set an output image filename and output HTML filename in Map Properties. I'd recommend you use the output folder as this is excluded from git updates (i.e enter output/mymap.png and output/mymap.html)**." does not appear to me what appears is "**Click here to access the editor where you can create and manage maps**."

When I click on the editor it shows me a welcome page to the PHP 0.97c editor but with a note that says: 

`NOTE: This editor is not finished! There are many features of Weathermap that you will be missing out on if you choose to use the editor only.These include: curves, node offsets, font definitions, colour changing, per-node/per-link settings and image uploading. You CAN use the editor without damaging these features if you added them by hand, however.`

Component | Version
--------- | -------
LibreNMS  | 1.42.01-58-g29d51f4
DB Schema | 259
PHP       | 7.0.30-0ubuntu0.16.04.1
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.7.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

Doubt 1. Where is "ensure Overlib is selected for HTML Style and click submit. "?
Doubt 2. Where is "ensure you set an output image filename and output HTML filename in Map Properties" ?

I followed https://docs.librenms.org/#Installation/Installation-Ubuntu-1604-Apache/ to install
I followed https://docs.librenms.org/#Extensions/Weathermap/#weathermapper to install the plugin

Thanks you for your support!!! =D

**Comment by howardjones** [comment]
It always has that note. It's not an error, just a fact.

Answer 1: it is in the main editor screen (Map Properties) after you have either selected an existing map file to edit, or created a new one.

Answer 2: Right below  Answer 1 :-)

Basically, you are 80% there. Under the warning, there should be a list of files (maybe empty), and an option to create a file (name it `something.conf`). Once you have done one of those two, you can actually edit the map.

**Comment by infovinicius** [comment]
My friend,

I called everyone in the company and I'm going to pay a pizza for anyone who finds Map Properties, can you send a print? =D

**Comment by infovinicius** [comment]
Nice Howrad =D

can I put any name in the image and in html?
