### ISSUE TITLE
Not Able to Create Maps Using Editor

### ISSUE THREAD

**Issue by ahosein868** [howardjones/network-weathermap#150]
Hey Guys,

I installed Weathermap 0.98a perfectly, but i can't get the Map editor to work. I can't add any Nodes or links, it's non functiional. Anyone' s assistance is greatly appreciated.

Cacti - 8.8f
PHP - 7.0.30
Plugin Architecture Version: 3.1
RRDTool - 1.5

**Comment by howardjones** [comment]
I'm going to guess you _didn't_ install it perfectly, and that the configs directory is not writable by the user that runs your webserver.

**Comment by ahosein868** [comment]
i have the configs dir writable by www-data but i still can't use the map editor, it just looks like a dummy screen, none of the buttons work, except for the one to show the config text. Are there any other versions you may have that i can try.

**Comment by howardjones** [comment]
Not with PHP 7.x, no.

That sounds like the Javascript part isn't loading, or failing quite early. Please check the javascript log in your browser (F12, if it's Chrome). Which 0.98a did you install? (there's a test number in the filename)

**Comment by netniV** [comment]
All browsers log their JavaScript errors to the Console log. Dependant on your browser, you will have a number of ways to get to this:

1. Right any element, select Inspect, then click the Console tab
   1. Firefox calls this Web Console or Browser Console
2. Using the menu button, normally top right
   1. Chorme's menu is three vertical dots, More Tools, Developer Tools
   2. Firefox's menu is three lines, Web Developer, Browser Console or Web Console
   3. Internet Explorer's menu is a settings cog, F12 Developer Tools
   4. Edge' smenu is three horizontal dots, Developer Tools
3. Using the keyboard by pressing Press Ctrl+Shift+J or F12 (or Cmd+Shift+J on a Mac)
   1. Internet Explorer only accepts F12
   2. Firefox accepts both, though Ctrl-Shift-J is only for Browser Log Window, not the developer tools
   3. Chrome and Edge accept both combinations.

If your log is clear, keep it open and refresh the page as sometimes browsers do not keep historical info of errors.  For firefox, you may need to check box the Browser log and the Console log

**Comment by ahosein868** [comment]
Hey Howie,

I'm using test1 (php-weathermap-0.98a-test1.zip). Here is a snapshot of the console portion of my browser, seeing there are some failed Jquery functions, any idea how i can get around this. Your help is greatly appreciated guys thx.


<img width="434" alt="console_cacti" src="https://user-images.githubusercontent.com/42588454/44594628-bea0ae80-a794-11e8-8ec5-58033839bf77.PNG">

![image](https://user-images.githubusercontent.com/42588454/44594643-cc563400-a794-11e8-9ab6-a3408d5af6dd.png)

**Comment by howardjones** [comment]
Could you retry with test4 please? I don't actually recall the specific changes between the test versions, but all the changes have been bugfixes!
