### ISSUE TITLE
network-weathermap - INCOMPLETE / Testing Api

### ISSUE THREAD

**Issue by koriks1111** [howardjones/network-weathermap#152]
Hi Howie, 

Can u help me finding out what is wrong, 

![image](https://user-images.githubusercontent.com/42999735/45088029-65446200-b13a-11e8-97b8-e352afbf7fdf.png)

weathermap  version 

1.0.0dev
--
cacti - Version 1.1.38
PHP 5.6.37 
![wm 1](https://user-images.githubusercontent.com/42999735/45088377-60cc7900-b13b-11e8-8beb-5d23624ef62d.png)
![wm 2](https://user-images.githubusercontent.com/42999735/45088378-60cc7900-b13b-11e8-84a0-790d2f1f6a13.png)

**Comment by koriks1111** [comment]
Hi,


i followed the instruction from github, i successfully installed, but when
i tried to open the weathermap, it shows incomplete

https://github.com/howardjones/network-weathermap



[image: image.png]


from Management here is the view
[image: image.png]

and after you click the Map List - or Settings or map Files it shows like
this
[image: image.png]

**Comment by koriks1111** [comment]
Hi, 


i followed the instruction from github, i successfully installed, but when i tried to open the weathermap, it shows incomplete

https://github.com/howardjones/network-weathermap


![image](https://user-images.githubusercontent.com/42999735/45093398-dbe95b80-b14a-11e8-8648-fca439183a2e.png)



from Management here is the view
![image](https://user-images.githubusercontent.com/42999735/45093409-e3a90000-b14a-11e8-8c09-f265df5c74fa.png)


and after you click the Map List - or Settings or map Files it shows like this

![image](https://user-images.githubusercontent.com/42999735/45093415-ead00e00-b14a-11e8-9900-0307840f634c.png)

**Comment by koriks1111** [comment]
Additional Screenshot from Weathermap tab

![image](https://user-images.githubusercontent.com/42999735/45093651-9a0ce500-b14b-11e8-9790-91455388197e.png)

This is the React UI below here
INCOMPLETE
(The Base URL is weathermap-cacti10-plugin.php?action=settings, passed from outside)
single map view (no group tabs, just a map) (and maybe a combo selector)

**Comment by howardjones** [comment]
Yes, it is not a finished version of Weathermap.

**Comment by koriks1111** [comment]
i see, may i know the link for finish version?

**Comment by howardjones** [comment]
There isn't one for Cacti 1.x yet.

**Comment by koriks1111** [comment]
i see, :'( i will just wait for the release
