### ISSUE TITLE
Plugin management not working

### ISSUE THREAD

**Issue by pautiina** [howardjones/network-weathermap#156]
Can not add  map to poller:
![image](https://user-images.githubusercontent.com/11805503/45616775-1a4f1680-ba79-11e8-82e6-f474386267dd.png)
Can not add group to poller:
![image](https://user-images.githubusercontent.com/11805503/45617029-c264df80-ba79-11e8-982c-5e471c785004.png)
The first time you open the settings, an error occurs:
![image](https://user-images.githubusercontent.com/11805503/45617119-ff30d680-ba79-11e8-81fc-5d35322f84cf.png)

**Comment by pautiina** [comment]
Can be fixed on https://github.com/howardjones/network-weathermap/pull/157

**Comment by pautiina** [comment]
Don't fix at last commit

**Comment by pautiina** [comment]
browser consol error fixed, but function not working

**Comment by howardjones** [comment]
This should be working now (I've been adding groups this weekend). You still can't move an existing map to a new group, but that's just because the code isn't there yet.

**Comment by pautiina** [comment]
In the settings there is still a lot of things not working, for example, I can not turn off or turn on the debug map.
Probably it is worth creating a separate issue for each functional, how do you think?

**Comment by howardjones** [comment]
It isn't finished. I guess there could be an issue for each missing item,
but it will be a lot of issues! This is the kind of thing github project
boards are for, but I haven't figured out how to choose which issues go on
a board yet.

**Comment by netniV** [comment]
If you create the project using one of the automated templates, you can search and add issues that are open via the "Add Cards".  I've created a test project for you on a test repo so you can see... you could have done the same but figured if I got one done, it gives you more of an idea.

**Comment by netniV** [comment]
https://github.com/netniV/project-test

**Comment by howardjones** [comment]
Thanks! Just trying to figure out if there's a pleasant way to turn a big text list into a lot of issues, all with the right labels.

**Comment by netniV** [comment]
You could use the github API to drag out the open issues or a specific post, then post the post feature.

**Comment by howardjones** [comment]
I'm going to try this: https://github.com/gavinr/github-csv-tools to create the issues with the right labels, at least.

**Comment by howardjones** [comment]
Well, I have 28 new issues lined up in a CSV file, anyway :-) Haven't quite figured out how to get them in yet.

**Comment by netniV** [comment]
You need to get an API token to use with index.js, then you just run that with nodejs I think...

**Comment by howardjones** [comment]
Yep - didn't have the right token permissions. Lots of nice new issues now, all sitting in the 1.0 and 1.1 release project boards.

**Comment by netniV** [comment]
You just spammed my many devices!! 👍 😆 🤣 😱

**Comment by netniV** [comment]
![Image](https://i.imgur.com/pNg0wsO.jpg)
