### ISSUE TITLE
Weathermap management only shows after the second click on the Weathermap menu option

### ISSUE THREAD

**Issue by pautiina** [howardjones/network-weathermap#162]
![image](https://user-images.githubusercontent.com/11805503/46333040-71cbb580-c627-11e8-9010-cb43c0ba0001.png)

Fixed on https://github.com/howardjones/network-weathermap/pull/157

**Comment by howardjones** [comment]
Agreed. Just waiting for the last requested (small) changes from Rutger and it will be merged.

**Comment by pautiina** [comment]
fixed https://github.com/howardjones/network-weathermap/commit/c43952f97da7ba517b8d281d54f221ad546c0f3d
