### ISSUE TITLE
Editor sets rrd_use_poller_output to false

### ISSUE THREAD

**Issue by RutgerLubbers** [howardjones/network-weathermap#164]
Given a configuration that has `rrd_use_poller_output` set to `1`, this property is set to `false` (`0`) after an edit. (For instance `094-test.conf` has this hint / property set.)

The git commit `846b5f6973a507e27a520a67e6dc02104a23053b` introduced some logic to fallback to the traditional rrdtool instead of using poller output. 

In RRDTool.php, line 51, a the map's context is checked to differ from the value `cacti`. Since the editor has the context `editor` the value for `rrd_use_poller_output` is set to `false` after each edit.

A bit further in the file (line 66) a map's context is checked against `cli`. So, would it be better to check the map's context to be equal to `cli` instead of not being equal to `cacti`?

I could create a PR for this, however I don't know how to check whether this does not reintroduce the issue that was solved by the git commit `846b5f6973a507e27a520a67e6dc02104a23053b`.

**Comment by RutgerLubbers** [comment]
All right, I think I can set this property in the RRDTool class. Would you like to discuss this here first, or should I create a PR and continue there?

**Comment by howardjones** [comment]
Go for it! It should be a pretty simple change.
