### ISSUE TITLE
Update visual appearance

### ISSUE THREAD

**Issue by Copse** [howardjones/network-weathermap#18]
I love weathermap but the visual appearance is kind of dated.

Compare this drawing (prob. Visio)
http://news.reannz.co.nz/wordpress/wp-content/uploads/2012/07/REANNZ_MAP_July12.jpg

To the real weathermap:
http://weathermap.reannz.co.nz/

If it could look more like the drawing that would be awesome. Smooth curved lines, modern fonts etc.

**Comment by howardjones** [comment]
This is where GD is starting to weigh us down. It has pretty bad font handling, and not-great anti-aliasing. I'd like to get to something like that too. I've been experimenting with SVG, but that also has some issues with fonts, unless you run javascript in the browser to generate the SVG. That said, I've got a nice SVG testbed for curved links, so far:

![construction](https://cloud.githubusercontent.com/assets/912421/6855941/6ce5fdf6-d3f4-11e4-9db0-f980637a11ee.png)

**Comment by howardjones** [comment]
I'm going to close this, and leave a pointer to #23 where there is discussion of allowing other rendering engines. The "modern fonts" part of your request is possible right now - it's just hard to package fonts with open source software for licensing.
