### ISSUE TITLE
Get confirmation from actual users for 0.98a-test4 so it can be a release.

### ISSUE THREAD

**Issue by howardjones** [howardjones/network-weathermap#198]
*I* think it should be fine, but it'd be really good to hear from real users that they are using it successfully, and I'll make that 0.98a official, for Cacti 0.8.8 users with a new OS (and PHP 7).

**Comment by SirMaple** [comment]
I've been using 0.98a-test4 for a month now and haven't had any issues.

System Details:

Cacti Version: 0.8.8f
Spine Version: 0.8.8b
OS: Ubuntu 16.04.5 LTS
RRDTool Version: 1.5.5
PHP Version: 5.6.36-1+ubuntu16.04.1+deb.sury.org+1
Apache Version: Apache/2.4.18 (Ubuntu)
MySQL Version: 5.7.23-0ubuntu0.16.04.1 - (Ubuntu)
