### ISSUE TITLE
Map access list not editable

### ISSUE THREAD

**Issue by aminelami** [howardjones/network-weathermap#203]
Hello,
I'm using:
Weathermap version 1.0.0dev
OS version CentOS 7
PHP version 7.1.22
Cacti version 1.1.38

I'm trying to test Weathermap 1.0.0dev on a production cacti. I can say it works great for me!
However the only issue I encountered is the Edit access list which is not editable.
I mean the created map is only viewable by the admin user, but not with other users although the permission to view the weathermap plugin was granted for that particular user.
The following popup is not editable:
![image](https://user-images.githubusercontent.com/43894743/47420862-b6a6c000-d77f-11e8-94aa-9ddbb4941544.png)

Could this be a bug or being worked on?

**Comment by howardjones** [comment]
Being worked on. Here's the todo list: https://github.com/howardjones/network-weathermap/projects/6

**Comment by aminelami** [comment]
ok thanks for the prompt reply !
