### ISSUE TITLE
Datasource external

### ISSUE THREAD

**Issue by vKnmnn** [howardjones/network-weathermap#204]
The datasource_external plugin references the WeatherMapDataSource class wich cannot be found. Did you maybe forget this one while refactoring?
I can't find the corresponding class, sadly, so i would be grateful for a fix.

Cheers

```
2018/12/11 15:07:34 - ERROR PHP ERROR in Plugin 'weathermap': Class 'WeatherMapDataSource' not found in file: /usr/local/share/cacti/plugins/weathermap/lib/Weathermap/Plugins/Datasources/WeatherMapDataSource_external.php on line: 23 
```

**Comment by howardjones** [comment]
Oops, I guess I did, because it's not normally a .php file, so phpstorm wouldn't have indexed it.

The new base class is just called 'Base'. If you look at the top of any of the other DS plugins, you'll see how it's supposed to look. Otherwise I'll push a change later.

**Comment by pautiina** [comment]
If fixed it's can be closed
