### ISSUE TITLE
weathermap 1.0.0dev Editor Stop to Work

### ISSUE THREAD

**Issue by rcsmota** [howardjones/network-weathermap#206]
Hi; 

Few weeks ago I instaled the weatermap 1.0.0dev on a Cacti 1.1.38 and all work great, I used use a editor without problem.

yesterday i tried edit a map but I'm recive the follow message.

![image](https://user-images.githubusercontent.com/31240306/52045692-f62e3680-253c-11e9-84e0-134af66c9e08.png)

Java is allowed on my browser and this is a console output 

![screen shot 2019-01-31 at 09 46 29](https://user-images.githubusercontent.com/31240306/52045844-3ee5ef80-253d-11e9-8f2f-2093b059e5ee.png)

I tried in some browsers and machines and now i dont sure the problem is on browser client or cacti server.

In the cacti log I have no errors. The Cacti is runnig on a Debina 9.

Thanks

**Comment by netniV** [comment]
Yeah I'm actually having the same issue today as I decided to try out the latest version and see where @howardjones has got up to 👍 

The chances are you've taken a copy from GitHub but not followed all the important developer steps that developers have to do (which I forgot about until I read this!)

https://github.com/howardjones/network-weathermap#using-the-dev-version

**Comment by netniV** [comment]
I think maybe we should add a link in the above message to the above just in case a user has installed the dev version.

**Comment by netniV** [comment]
@rcsmota if you download the latest weathermaps, you should see an updated message now.

**Comment by rcsmota** [comment]
Hi @netniV 

Sorry for delay. I'll try it now.
