### ISSUE TITLE
Weathermap editor does not use graph names when trying to select from list.

### ISSUE THREAD

**Issue by jdcoats** [howardjones/network-weathermap#211]
Cacti 1.2.2 dev and latest dev weathermap. When trying to edit a weathermap with the GUI the interface map names are not used making it impossible to know which link you are choosing.
![connectivity](https://user-images.githubusercontent.com/42470924/54073326-d4b71d80-4253-11e9-9257-caf45958708e.png)
![GraphNames](https://user-images.githubusercontent.com/42470924/54073327-d8e33b00-4253-11e9-9f3d-03a597d9913a.png)

**Comment by howardjones** [comment]
It gets the names from the Data Sources, not the Graphs. What do your Data Sources look like? (they have their own naming rules)

**Comment by jdcoats** [comment]
Thanks, For some reason Cacti isn't updating the DS name even though I have updated the template, sync'd and re-applied names. Closing this as user error or training. I'll try to figure out why the DS name isn't updating. I don't want to have to delete and re-create :)

**Comment by jpobeda** [comment]
@jdcoats there was a bug affecting the re-apply suggested name thing for DS and graphs. It was fixed but on one of those 1.2.x versions I think..I'm still on 1.1.37 though, it's so bloody hard to keep up without breaking plugins along the way....
