### ISSUE TITLE
cant install on cacti 1.2.4

### ISSUE THREAD

**Issue by ahiyaz** [howardjones/network-weathermap#228]
hi

ive tried to install weathermap on cacti 1.2.4 but got this error.
plugin ver is 1.0.0dev
appreciate your help

**Sorry, we could not process your last action.
Error:
500 Internal Server Error
Reason:
The response to the last action was unexpected.**

**Comment by ahiyaz** [comment]
![weathermap](https://user-images.githubusercontent.com/54144882/63099666-33f52880-bf7e-11e9-8246-9615ff8bb0c5.JPG)

**Comment by howardjones** [comment]
So I know you read the bug report template before you deleted it... how about 

> - Any error message you got, including:
> 
>   - Errors in httpd error_log
>   - Warnings in cacti.log (or equivalent)
>   - Any error messages in the browser javascript console, for editor/web issues (e.g. press F12 in Chrome)

? 500 Server Error will usually also result in an error message in the webserver error log.

**Comment by ahiyaz** [comment]
ok
i went trough the README.md and now the installation succeeded.
thanks

**Comment by netniV** [comment]
Amazing what a bit of RTFM can do ;-)
