### ISSUE TITLE
Weathermap CACTI 1.2.7

### ISSUE THREAD

**Issue by tatcar55** [howardjones/network-weathermap#231]
Hi

I install weathermap on cacti 1.2.7 Centos 7, but I have some problems. can you help me please?

![Captura1](https://user-images.githubusercontent.com/20170202/66836734-7d82d500-ef27-11e9-987a-19f398ae90f0.PNG)

- In the management and view show this errror: This is the React UI below here
INCOMPLETE
![Captura2](https://user-images.githubusercontent.com/20170202/66837016-f1bd7880-ef27-11e9-8f7c-e90eb45f4f35.PNG)

- It does not show sample configuration files 
![Captura3](https://user-images.githubusercontent.com/20170202/66837213-3fd27c00-ef28-11e9-8316-a1260088b8a9.PNG)

- I can't create new maps and edit maps

- Errors from cacti.log

2019/10/15 08:51:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[750]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_poller_bottom(), /plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti-plugin-poller.php[176]:Weathermap\Poller\runMaps(), /plugins/weathermap/lib/Weathermap/Poller/poller-common.php[84]:Weathermap\Poller\MapRuntime->run(), /plugins/weathermap/lib/Weathermap/Poller/MapRuntime.php[148]:Weathermap\Core\Map->readData(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1569]:Weathermap\Core\Map->readDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1513]:Weathermap\Core\MapDataItem->performDataCollection(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[232]:Weathermap\Core\MapDataItem->collectDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[264]:Weathermap\Core\Target->readData(), /plugins/weathermap/lib/Weathermap/Core/Target.php[124]:Weathermap\Plugins\Datasources\CactiHostStatus->readData(), /plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php[93]:CactiErrorHandler())
--
2019/10/15 08:51:10 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined variable: statename in file: /var/www/html/cacti-1.2.7/plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php on line: 93
2019/10/15 08:50:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[796]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_poller_bottom(), /plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti-plugin-poller.php[176]:Weathermap\Poller\runMaps(), /plugins/weathermap/lib/Weathermap/Poller/poller-common.php[84]:Weathermap\Poller\MapRuntime->run(), /plugins/weathermap/lib/Weathermap/Poller/MapRuntime.php[148]:Weathermap\Core\Map->readData(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1569]:Weathermap\Core\Map->readDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1513]:Weathermap\Core\MapDataItem->performDataCollection(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[232]:Weathermap\Core\MapDataItem->collectDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[264]:Weathermap\Core\Target->readData(), /plugins/weathermap/lib/Weathermap/Core/Target.php[124]:Weathermap\Plugins\Datasources\CactiHostStatus->readData(), /plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php[93]:CactiErrorHandler())
2019/10/15 08:50:41 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined variable: statename in file: /var/www/html/cacti-1.2.7/plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php on line: 93
2019/10/15 08:50:12 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[750]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_poller_bottom(), /plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti-plugin-poller.php[176]:Weathermap\Poller\runMaps(), /plugins/weathermap/lib/Weathermap/Poller/poller-common.php[84]:Weathermap\Poller\MapRuntime->run(), /plugins/weathermap/lib/Weathermap/Poller/MapRuntime.php[148]:Weathermap\Core\Map->readData(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1569]:Weathermap\Core\Map->readDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1513]:Weathermap\Core\MapDataItem->performDataCollection(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[232]:Weathermap\Core\MapDataItem->collectDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[264]:Weathermap\Core\Target->readData(), /plugins/weathermap/lib/Weathermap/Core/Target.php[124]:Weathermap\Plugins\Datasources\CactiHostStatus->readData(), /plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php[93]:CactiErrorHandler())
2019/10/15 08:50:12 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined variable: statename in file: /var/www/html/cacti-1.2.7/plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php on line: 93
2019/10/15 08:49:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[796]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_poller_bottom(), /plugins/weathermap/lib/Weathermap/Integrations/Cacti/cacti-plugin-poller.php[176]:Weathermap\Poller\runMaps(), /plugins/weathermap/lib/Weathermap/Poller/poller-common.php[84]:Weathermap\Poller\MapRuntime->run(), /plugins/weathermap/lib/Weathermap/Poller/MapRuntime.php[148]:Weathermap\Core\Map->readData(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1569]:Weathermap\Core\Map->readDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/Map.php[1513]:Weathermap\Core\MapDataItem->performDataCollection(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[232]:Weathermap\Core\MapDataItem->collectDataFromTargets(), /plugins/weathermap/lib/Weathermap/Core/MapDataItem.php[264]:Weathermap\Core\Target->readData(), /plugins/weathermap/lib/Weathermap/Core/Target.php[124]:Weathermap\Plugins\Datasources\CactiHostStatus->readData(), /plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php[93]:CactiErrorHandler())
2019/10/15 08:49:42 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined variable: statename in file: /var/www/html/cacti-1.2.7/plugins/weathermap/lib/Weathermap/Plugins/Datasources/CactiHostStatus.php on line: 93

![Captura4](https://user-images.githubusercontent.com/20170202/66837730-15cd8980-ef29-11e9-81d4-ab676f134994.PNG)

**Comment by howardjones** [comment]
This is all expected. It's unfinished.

**Comment by tatcar55** [comment]
Could there be a solution? or it's not possible on cacti 1.2.7

**Comment by howardjones** [comment]
It isn't possible on Cacti 1.x right now. I'm working on a version that will, but it's going slowly.

**Comment by tatcar55** [comment]
OK thank you very much

**Comment by netniV** [comment]
Once Howie has finished his UI/Core separation, I'll be working on the Cacti UI part so it keeps with Cacti's normal standards.  

The idea is to free up Howie's time by not making him worry about ever changing UI standards and keeping the core working well against any of its sources/integrations. 👍 

There's a lot of work for both of us, unfortunately, and its our free time that we give up to do it when we can, which isn't always easy after a long hard day at the office or when family life wants/needs/demands our attention.

The good news is that the runtime works well and Howie's done a great job on that.
