### ISSUE TITLE
Any workaround for changing SNMP Indexes ?

### ISSUE THREAD

**Issue by edvinaskairys** [howardjones/network-weathermap#232]
Hello,

We're using Network Weathermap with Observium, we started to monitor some Linux server interfaces, but after server reboot the if indexes of the server changes. And after that i need to set new value of that particular interface.

So. my question would be is there any workaround from Network weathermap perspective ?

Thanks

**Comment by howardjones** [comment]
Does Observium rename its rrd files at that point?
What are you using as a TARGET string in Weathermap?

**Comment by edvinaskairys** [comment]
yes, observium creates new rrd file for that port. For example it was port-14.rrd. After linux reboots it gets port-16.rrd.  And port ID also changes.

**Comment by netniV** [comment]
You may need to check the index that you are using within Observium.  For example, you may find that ifAlias gives you a changing index but ifName keeps things consistent.

**Comment by zombah** [comment]
I don't know about Observium but LibreNMS which is Observium open source fork allow to choose this as _Port Association Mode_ on device addition with options ifIndex,ifName,ifDescr or ifAlias.
