### ISSUE TITLE
Overlib Issue

### ISSUE THREAD

**Issue by jakkarta0990** [howardjones/network-weathermap#239]
Hi there,

I have setup weathermap on my server and it everything seems to be working except for the "overlib" feature.

I have checked online for issues related to this and the solution has always been to add:

`"HTMLSTYLE overlib"`

It's add the top of the config as instructed yet hovering over a link doesn't bring up the related graph.

An example link in my config:

```
LINK VKN-EXT-AGG_YTS-EXT-AGG-1
        INFOURL http://172.16.193.72/cgi-bin/routers2.cgi?if=172.16.193.105_TenGigabitEthernet1_1_13&xgtype=w&rtr=Cisco-6500-EXT-AGG.cfg
        OVERLIBGRAPH http://172.16.193.72/graphs/Cisco-6500-EXT-AGG.cfg-172.16.193.105_TenGigabitEthernet1_1_13-w-x3.png
        TARGET /var/mrtg/172.16.193.105_tengigabitethernet2_1_13.rrd
        NODES 6969 142
        VIA 791 500
        BANDWIDTH 200M
```
My weathermap is trying to link to my MRTG rrds, so I'm not sure if that makes a difference. RRDs and links to graph upon clicking on a link or node are working work. All except for this hover-graph feature.

**Details re my setup**:

> Weathermap Version: 0.98a
> Host platform: (Ubuntu 18.04LTS, PHP7.2, MRTG with Apache2)

The error message I'm getting from my Chrome console is:

_Uncaught ReferenceError: overlib is not defined
    at HTMLAreaElement.onmouseover (goextnet.map.html:113)_

Appreciate any help!

**Comment by howardjones** [comment]
Is there a copy of `overlib.js` in the directory where the maps are written?

**Comment by jakkarta0990** [comment]
There is. It's in the main weathermap directory itself.

The configs and html/png outputs are stored in the subdirectories (i.e. configs/ and outputs/ respectively).

If it helps the weathermap directory is:

/var/www/html/weathermap

**Comment by howardjones** [comment]
Have a look at the top of the HTML file. I'm pretty sure it's expecting to find the overlib.js in the same directory as the HTML file itself if you are generating standalone output (i.e. not with Cacti).

**Comment by jakkarta0990** [comment]
That absolutely did it!

Thanks a bunch!
