### ISSUE TITLE
Unable to view Realtime Graph in Weathermap

### ISSUE THREAD

**Issue by sdiwakar123** [howardjones/network-weathermap#252]
Hello,

I am using Cacti 1.2.14 with weathermap 1.x . everything works fine except realtime graph in weathermap, while realtime graph in cati works fine. 
I have checked cacti logs where it shows error "

2020/12/29 14:17:51 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"29.4M","config-read":"30.4M","settings-set":"30.4M","data-read":"30.4M","post-render":"15.7M","end":"15.7M"},"times":{"start":1609231671.226824,"config-read":1609231671.231607,"settings-set":1609231671.2322011,"data-read":1609231671.375627,"post-render":1609231671.681639,"end":1609231671.6851411},"stats":{"total_targets":27,"duration":0.45831704139709473,"warnings":0}}
--
2020/12/29 14:17:51 - WEATHERMAP WARNING: ReadData: [LINK NM-CHANDIVALI-MCPL-1], target: /usr/share/cacti/rra/ciena_mcpl-1_traffic_in_743.rrd had no valid data, according to RRDTool [WMWARN70]
2020/12/29 14:17:51 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"27.3M","config-read":"28M","settings-set":"28M","data-read":"28M","post-render":"29.4M","end":"29.4M"},"times":{"start":1609231670.838779,"config-read":1609231670.8433039,"settings-set":1609231670.8439209,"data-read":1609231670.9363461,"post-render":1609231671.223587,"end":1609231671.2261801},"stats":{"total_targets":17,"duration":0.38740110397338867,"warnings":0}}
2020/12/29 14:17:50 - WEATHERMAP WARNING: ReadData: [LINK MCPL-1-node04307], target: /usr/share/cacti/rra/ciena_mcpl-1_traffic_in_752.rrd had no valid data, according to RRDTool [WMWARN70]
2020/12/29 14:17:50 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"24.8M","config-read":"26.2M","settings-set":"26.2M","data-read":"26.3M","post-render":"27.3M","end":"27.3M"},"times":{"start":1609231670.307899,"config-read":1609231670.314471,"settings-set":1609231670.3150189,"data-read":1609231670.47856,"post-render":1609231670.83533,"end":1609231670.8381159},"stats":{"total_targets":30,"duration":0.53021693229675293,"warnings":0}}
2020/12/29 14:17:50 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"20.4M","config-read":"21.4M","settings-set":"21.4M","data-read":"21.5M","post-render":"24.8M","end":"24.8M"},"times":{"start":1609231669.8181081,"config-read":1609231669.823606,"settings-set":1609231669.824167,"data-read":1609231669.9990439,"post-render":1609231670.3027,"end":1609231670.3072469},"stats":{"total_targets":32,"duration":0.48913884162902832,"warnings":0}}
2020/12/29 14:17:49 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"32.9M","config-read":"35.2M","settings-set":"35.2M","data-read":"35.3M","post-render":"20.4M","end":"20.4M"},"times":{"start":1609231669.0750871,"config-read":1609231669.084023,"settings-set":1609231669.08463,"data-read":1609231669.460139,"post-render":1609231669.808531,"end":1609231669.8174},"stats":{"total_targets":71,"duration":0.74231290817260742,"warnings":0}}
2020/12/29 14:17:49 - WEATHERMAP WARNING: ReadData: [LINK LVSB-node04241], target: /usr/share/cacti/rra/ciena_tata_bkc-1_traffic_in_828.rrd had no valid data, according to RRDTool [WMWARN70]
2020/12/29 14:17:49 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"32.1M","config-read":"32.6M","settings-set":"32.6M","data-read":"32.7M","post-render":"32.9M","end":"32.9M"},"times":{"start":1609231668.710681,"config-read":1609231668.7151561,"settings-set":1609231668.71574,"data-read":1609231668.7708559,"post-render":1609231669.072773,"end":1609231669.07424},"stats":{"total_targets":10,"duration":0.36355900764465332,"warnings":0}}

" 

Please help.
Thank you
Sushant
![realtime](https://user-images.githubusercontent.com/76724933/103271878-6cfe3380-49e1-11eb-97c0-dfe529cdfcff.png)

**Comment by howardjones** [comment]
1) There is no version "1.x" of weathermap. What are you actually running?
2) None of those are errors.
3) What does your weathermap map file look like (for one link that you think should have a realtime graph)?

**Comment by sdiwakar123** [comment]
@howardjones Weathermap version is 1.0.0dev.
 whenever i try to open any link graph in realtime it won't open. 
we have arround 14 to 15 weathermap. basically monitoring our Network.

**Comment by howardjones** [comment]
What do you mean by "opening a link graph in realtime"? Nothing in Weathermap knows anything special about the Realtime plugin. Please paste the config for a link that has this problem.

(Also, you might be hitting some problem between the unreleased weathermap you're using and Cacti 1.2)

**Comment by sdiwakar123** [comment]
when i open any link on one of my network weathermap there is option to view realtime graph of that link. which is not opening due to php memory error.

**Comment by howardjones** [comment]
Maybe should have mentioned the php memory error before... (unless you mean what you posted in the first place - that isn't an error, just statistics)

So it doesn't sound like it's anything to do with weathermap. You click on a graph and then on the graph page you get a memory error. I guess just increase memory_limit in your php.ini, restart the webserver service and see how that works. Weathermap doesn't use much memory at all in the webserver process - all the memory use is in the poller process, which is temporary for each poll.

**Comment by sdiwakar123** [comment]
@howardjones  i have already increased upto 2GB memory in php.ini file. but still no luck.

**Comment by howardjones** [comment]
Please post the error.

**Comment by sdiwakar123** [comment]
2021/01/11 17:17:10 - WEATHERMAP About to write image file. If this is the last message in your log, increase memory_limit in php.ini () [WMPOLL01] : memory_get_usage() says 26MBytes used. Limit is -1
--
2021/01/11 17:17:10 - WEATHERMAP WARNING: ReadData: [LINK SAI_BABA_BULDHANA_1G-node00661], target: /usr/share/cacti/rra/58/1018.rrd had no valid data, according to RRDTool [WMWARN70]
2021/01/11 17:17:10 - WEATHERMAP Map: /usr/share/cacti/plugins/weathermap/configs/BW_customer.conf -> /usr/share/cacti/plugins/weathermap/output/801526afb0a45a05c6ac.html & /usr/share/cacti/plugins/weathermap/output/801526afb0a45a05c6ac.png
**2021/01/11 17:17:10 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"23.3M","config-read":"24.2M","settings-set":"24.2M","data-read":"24.3M","post-render":"24.9M","end":"24.9M"},"times":{"start":1610365629.9898269,"config-**read":1610365629.9944561,"settings-set":1610365629.994982,"data-read":1610365630.122746,"post-render":1610365630.4157629,"end":1610365630.4178071},"stats":{"total_targets":20,"duration":0.42798018455505371,"warnings":0}}

**Comment by howardjones** [comment]
Is it the last message in your log? I don't think it is if you are getting map images.

Also, if you get an error *when you click on the realtime icon* it would be in the webserver error logs, not the cacti.log.

**Comment by sdiwakar123** [comment]
@howardjones  Thanks for your help. It seems issue is related to Cacti not Weathermap.
