### ISSUE TITLE
Give Cacti User Read-only access of single weather Map 

### ISSUE THREAD

**Issue by sdiwakar123** [howardjones/network-weathermap#258]
Hi
I am using Cacti version 1.2.14 on Centos7 , I want to give a normal cacti user read only access of one weathermap in Cacti. Please help.

Thanks

**Comment by howardjones** [comment]
I don't know if this has changed in Phalek's fork (for Cacti 1.2) but it should be:

Click on the list of users (where it says 'admin', usually) next to the map in the management screen, add the user. Give that user "View Weathermaps" permission in Cacti.

If you want hover graphs to work for them, they will also need permission to view those graphs.

**Comment by sdiwakar123** [comment]
@howardjones  That setting is already enabled in Cacti Settings. But no Weathermap is shown.
![image](https://user-images.githubusercontent.com/76724933/106560113-7e8cab00-654c-11eb-9892-6d8069fc5013.png)

**Comment by howardjones** [comment]
Don't use the github version of weathermap. It literally says it's INCOMPLETE in big letters in the middle of the screen. :-)

You should give this a try instead:
https://www.network-weathermap.com/2020/09/18/weathermap-0-98a-adapted-for-cacti-1-x/
