### ISSUE TITLE
cacti-integrate.php - use-dsstats logic is reversed

### ISSUE THREAD

**Issue by TxEdgeMan** [howardjones/network-weathermap#26]
In  random-bits/cacti-integrate.php  the logic for generating the target should be reversed:
current code reads:

if ($use_dsstats) {
....
} else { 
   $tgt = "8*dsstats:$local_data_id" . $ds_names;
....
}

when $use_dsstats is true is should use the contents of the second clause, not the first.

**Comment by howardjones** [comment]
Thanks for the report! This is resolved in the current dev version, via commit ec10d756c54939e2444f529fb3c481e27493bca1

**Comment by TxEdgeMan** [comment]
Hi Howie,
Awesome tool!  The deeper I dive into it the more I love it!.  I might be missing something, but I don't see where the referenced commit touches that file or anything to do with dsstats for that matter.
Cheers,

Chris

**Comment by howardjones** [comment]
Sorry! I think I must have pasted the wrong commit... it's here: 4938a007d35a07c2bae3ed8d9843ce50ff218aac

**Comment by howardjones** [comment]
Sorry - pasted, the wrong commit. I meant here: 4938a007d35a07c2bae3ed8d9843ce50ff218aac

The change is slightly different (I switched $use_dsstats with !$use_dsstats), but the logic is the same.

Glad you like it!
