### ISSUE TITLE
how to display the bandwith graphs (overlib) on the left side of the mouse?

### ISSUE THREAD

**Issue by maechi** [howardjones/network-weathermap#29]
I have a rather large map with several nodes and links on the right side of the map. when i mouse-over the link, tha bandwith graphs are "hidden" outside of the browser window. If I resize the browser window i see the whole graph.

Is there a config option to display the overlib graph on the left side of the mouse?

![weathermap](https://cloud.githubusercontent.com/assets/570371/11784494/d6d58220-a27c-11e5-932c-2135c3c3646b.jpg)

I'm using the phpweathermap V0.97c on a FreeBSD System

**Comment by howardjones** [comment]
Depending on how much is hidden... 
http://network-weathermap.com/manual/0.97b/pages/faq.html#overliboffscreen

But this works based on where the graph is relative to the centre of the map image, not the screen.

**Comment by maechi** [comment]
Hi Howard
Thank you very much for the help. I read the FAQ but dond't find that command usefull. Know that O know the reason behin this it all makes sense.

Thank you very much for your help
