### ISSUE TITLE
Editor resources 404

### ISSUE THREAD

**Issue by hakong** [howardjones/network-weathermap#30]
editor.js and editor.css are located in editor-resource/ but editor.php tries to load them in ./
Can anyone reproduce this? Got version 0.97b.
I fixed it and now it looks like:
![image](https://cloud.githubusercontent.com/assets/4422113/12350965/4b3aa5f6-bb72-11e5-8754-054ecb4b08ec.png)

**Comment by howardjones** [comment]
This is already fixed in 0.97c

**Comment by hakong** [comment]
Thanks! I'll wait for a 0.97c release :smile:

**Comment by howardjones** [comment]
No need to wait. It has been out for several years!

**Comment by hakong** [comment]
Where can I find it? Latest I see is 0.97b:
![image](https://cloud.githubusercontent.com/assets/4422113/12351638/fbac479c-bb76-11e5-906c-593c2aa608d5.png)

**Comment by howardjones** [comment]
Hmm, not sure why there is no tag... it's on the website:
http://www.network-weathermap.com/

**Comment by howardjones** [comment]
Working backwards, it's commit 475e9c88aa674d4589311f4c0ec1a5a2010d70bc but it wasn't tagged. This would have been from the subversion repo (there hasn't been a release from github yet)
