### ISSUE TITLE
PHP8 Deprecations

### ISSUE THREAD

**Issue by mnews-jeffrey** [howardjones/network-weathermap#302]
I used PHP 8.1 when I tried to output the png and html got these errors
does anyone get the same issue as me?

root@librenms:/opt/librenms/html/plugins/Weathermap# ./weathermap.php --config configs/mnewstv.conf --output output/mnewstv.png --htmloutput output/mnewstv.html
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/php/Console/Getopt.php on line 313
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/php/Console/Getopt.php on line 313
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/php/Console/Getopt.php on line 313
PHP Deprecated:  Function strftime() is deprecated in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 3287
PHP Deprecated:  Implicit conversion from float 49.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 41.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 74.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 58.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 49.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 41.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 74.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 58.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 51.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 43.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 42.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 41.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 81.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 58.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 42.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 41.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 81.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 58.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 44.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 43.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 23.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 40.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 635
PHP Deprecated:  Implicit conversion from float 23.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 40.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMapNode.class.php on line 649
PHP Deprecated:  Implicit conversion from float 25.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  Implicit conversion from float 433.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  Implicit conversion from float 333.5 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  Implicit conversion from float 404.25 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 530.25 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  imagefilledpolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1926
PHP Deprecated:  imagepolygon(): Using the $num_points parameter is deprecated in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1906
PHP Deprecated:  Implicit conversion from float 306.75 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 623.75 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 5.600000000000001 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 27.6 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 45.2 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 29.200000000000003 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 47.2 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 64.80000000000001 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 48.80000000000001 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 66.80000000000001 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 84.4 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 68.4 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 86.4 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 123.6 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 107.6 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 125.60000000000001 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 143.20000000000002 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 127.20000000000002 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 145.20000000000002 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 162.8 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 146.8 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Implicit conversion from float 164.8 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 182.4 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.functions.php on line 1874
PHP Deprecated:  Implicit conversion from float 166.4 to int loses precision in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 506
PHP Deprecated:  Function strftime() is deprecated in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 1720
PHP Deprecated:  Function strftime() is deprecated in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 1725
PHP Warning:  Undefined property: WeatherMap::$basehref in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 307

**Comment by howardjones** [comment]
I am slowly working through 8.1 deprecation issues in the 0.98-php8 branch. It is still wrong for strftime-related stuff, at least, but these float/int issues should be taken care of. strftime looks like it will require me writing my own, to keep compatibility.

**Comment by mnews-jeffrey** [comment]
Hi Howard,

Thanks for your information.
I'm looking forward to seeing this fix for php8.1.

Because of the upgrade to php8.1 that cause my weathermap even can not
drawing any pic in my plugging system.

Best Regards,
Jeffrey
ᐧ

Howard Jones ***@***.***> 於 2022年8月22日 週一 下午5:42寫道：

> I am slowly working through 8.1 deprecation issues in the 0.98-php8
> branch. It is still wrong for strftime-related stuff, at least, but these
> float/int issues should be taken care of.
>
> —
> Reply to this email directly, view it on GitHub
> <https://streaklinks.com/BLBxDBBVlch1cQPYJQfM0qKe/https%3A%2F%2Fgithub.com%2Fhowardjones%2Fnetwork-weathermap%2Fissues%2F302%23issuecomment-1222110513>,
> or unsubscribe
> <https://streaklinks.com/BLBxDBN5OZDdYqJMPACZd4zh/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUXXEMWEKLOLAIBAOC3QWB3V2NDRXANCNFSM567NLBDA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>
ᐧ
