### ISSUE TITLE
Maps not showned in plugin tab after upgrade 0.97c->0.98

### ISSUE THREAD

**Issue by cosu77** [howardjones/network-weathermap#31]
Hello,

Yesterday, after network-weathermap upgrade (0.97c->0.98), my maps are freezed at 08:05AM.
Even so the files in output directory are updated:
24 -rw-r--r--  1 cactiuser cactiuser 24373 Jun  3 11:15 040ae8b1624617bd7da3.html
28 -rw-r--r--  1 cactiuser cactiuser 25469 Jun  3 11:15 040ae8b1624617bd7da3.png
 4 -rw-r--r--  1 cactiuser cactiuser  1032 Jun  3 11:15 040ae8b1624617bd7da3.results.txt
12 -rw-r--r--  1 cactiuser cactiuser 10294 Jun  3 11:15 040ae8b1624617bd7da3.thumb.png
32 -rw-r--r--  1 cactiuser cactiuser 31371 Jun  3 11:15 0e08b428f2362608fb02.html
28 -rw-r--r--  1 cactiuser cactiuser 28551 Jun  3 11:15 0e08b428f2362608fb02.png
 4 -rw-r--r--  1 cactiuser cactiuser  1323 Jun  3 11:15 0e08b428f2362608fb02.results.txt
Those file  are perfectly viewed from explorer.

In cacti.log file:
06/03/2016 11:20:21 AM - WEATHERMAP: Poller[0] [Map 141] map.conf: Map: /var/www/localhost/htdocs/cacti-0.8.8h/plugins/weathermap/configs/map.conf -> /var/www/localhost/htdocs/cacti-0.8.8h/plugins/weathermap/output/1fc33f91f3df819f1f5f.html & /var/www/localhost/htdocs/cacti-0.8.8h/plugins/weathermap/output/1fc33f91f3df819f1f5f.png
06/03/2016 11:20:22 AM - WEATHERMAP: Poller[0] [Map 141] map.conf: About to write image file. If this is the last message in your log, increase memory_limit in php.ini [WMPOLL01]
06/03/2016 11:20:22 AM - WEATHERMAP: Poller[0] [Map 141] map.conf: Wrote map to /var/www/localhost/htdocs/cacti-0.8.8h/plugins/weathermap/output/1fc33f91f3df819f1f5f.png and /var/www/localhost/htdocs/cacti-0.8.8h/plugins/weathermap/output/1fc33f91f3df819f1f5f.thumb.png
06/03/2016 11:20:22 AM - WEATHERMAP: Poller[0] STATS: Weathermap 0.98 run complete - Fri, 03 Jun 16 11:20:22 +0300: 20 maps were run in 13 seconds with 5 warnings.

In cacti, weathermap tab i have a strange thing:
Powered by PHP Weathermap version 0.97c --- Weathermap Management | Local Documentation | Editor
and all maps freezed at date: Jun 2 2016 08:05 AM, the date&time before upgrade.

What can i do? It's from cacti or from plugin?

Thank you & sorry for my unexercised english.

**Comment by cosu77** [comment]
![capture](https://cloud.githubusercontent.com/assets/19723479/15773640/bd5010fa-2980-11e6-9631-daaa2c849309.PNG)

**Comment by howardjones** [comment]
That's an interesting bug!

So permissions must be OK, because you are getting new files.

*  Have you checked the contents of those files? What is the datestamp in those .png images?
*  What is your environment? What PHP, Apache, Linux versions?
*  Did you upgrade anything else at the same time?

**Comment by howardjones** [comment]
In your screenshot, the version is still 0.97c. Maybe something didn't get replaced correctly?

**Comment by cosu77** [comment]
In the .png/.html files i have all my wmaps. Datestamp looks like this:
output/9057c301e9047cbe760b.png was last modified: 1464955812
output/9057c301e9047cbe760b.png was last modified: June 03 2016 15:10:12

Environment:
Linux Gentoo with kernel 4.4.6-gentoo
PHP 5.6.21-pl0-gentoo (with GD and memory limit @512M)
Lighttpd 1.4.35-r1
Catci 0.8.8h (upgraded yesterday at 7:15, after upgrade 0.97c works just fine)

Info from your check script:
----------------------------------------------------
Weathermap Pre-Install Checker

This script checks for some common problems with your PHP and server
environment that may stop Weathermap or the Editor from working.

NOTE: You should run this script as both a web page AND from the
command-line, as the environment can be different in each.

This is the PHP version that is responsible for 
* creating maps from the Cacti poller
* the command-line weathermap tool

PHP Basics
----------
This is PHP Version 5.6.21-pl0-gentoo running on "Linux grafice
4.4.6-gentoo #1 SMP Tue Apr 26 15:12:05 EEST 2016 i686" with a memory_limit
of '512M'. 

The php.ini file was /etc/php/cli-php5.6/php.ini
The following additional ini files were read: /etc/php/cli-php5.6/ext-active/opcache.ini


PHP Functions
-------------
Some parts of Weathermap need special support in your PHP
installation to work.

This PHP uses the 'bundled' GD library, which doesn't have alpha-blending
bugs. That's good!

The Console_Getopt PEAR module is available. That's good!

            imagepng   YES                                                     
imagecreatetruecolor   YES                                                     
  imagealphablending   YES                                                     
      imageSaveAlpha   YES                                                     
          preg_match   YES                                                     
  imagecreatefrompng   YES                                                     
 imagecreatefromjpeg   YES                                                     
  imagecreatefromgif   YES                                                     
           imagejpeg   YES                                                     
            imagegif   YES                                                     
  imagecopyresampled   YES                                                     
        imagettfbbox   YES                                                     
    memory_get_usage   YES                                                     

---------------------------------------------------------------------
OK! Your PHP and server environment *seems* to have support for ALL of the
Weathermap features. Make sure you have run this script BOTH as a web page
and from the CLI to be sure, however.

Upgrade process:
- uninstall 0.97c in cacti Plugin Management
- moving the wethermap directory from plungins
- download 0.98 version, unziped, copy images&configs from old director
- install and activate in cacti Plugin Management
- checking and setting rights

Seems to be just a display problem, before this issue i tried to go back to 0.97c (no succes). Now i'm running 0.98.

**Comment by howardjones** [comment]
No, I meant what is the date IN the images? If you open one of those png files in the output directory,
What is the time stamp on the map?

This sounds like some kind of caching problem - there is only one copy of the image files,so if the
output directory is being updated, the only other place that file can exist is your browser's cache.

**Comment by cosu77** [comment]
This is timestamp on 9057c301e9047cbe760b.png
![timestamp](https://cloud.githubusercontent.com/assets/19723479/15790077/1f305260-29d8-11e6-9529-e774839d107c.PNG)
Timestamp is changing every 5 minutes.
I tried loading cacti in 3 different explorers, Ctrl+Shift+Reload, clear cache, basic stuff in some kind of situations.

I can't understand this on my cacti page:
Powered by PHP Weathermap version 0.97c --- Weathermap Management | Local Documentation | Editor
after:
```
# pwd
/var/www/localhost/htdocs/cacti/plugins/weathermap
# grep "0.97c" * -R
CHANGES:0.97c had no additional changes - it's just 0.97b with some silly errors fixed, and  all
... snip: configs/*:# Automatically generated by php-weathermap v0.97c ...
docs/pages/changes.html: <h2 id="changes098">Changes For This Version (0.97c to 0.98)</h2> 
docs/pages/changes.html: <h2 id="changes097c">Changes For This Version (0.97b to 0.97c)</h2> 
docs/pages/changes.html: <p>0.97c had no additional changes - it's just 0.97b with some silly errors fixed, and all
```
![capture](https://cloud.githubusercontent.com/assets/19723479/15773640/bd5010fa-2980-11e6-9631-daaa2c849309.PNG)
some stuff generated by plugin, nothing related to explorer's cache.

**Comment by howardjones** [comment]
Ok.. From basics :-) 

grep 0.97c *.php lib/*.php

On my system, that produces no output.

**Comment by howardjones** [comment]
Never mind - I missed the bottom of the previous mail.

Have you restarted apache since the upgrade? It shouldn't be necessary, but that's the only other thing I can think of where old data might be hanging around.

**Comment by cosu77** [comment]
OMG :)
I never needed something like this, server restart. I do it right now and ... magic, there are my maps.
Thanx a lot!
