### ISSUE TITLE
How  to draw a ServerRack

### ISSUE THREAD

**Issue by zjsparkle** [howardjones/network-weathermap#32]
I saw in the weathermap propaganda content to see a server rack map, this is how to draw it? Request for comment

**Comment by howardjones** [comment]
I will post a demo of it, but it's very simple - the rack is made of nodes with lower zorder and a 'rect' icon type, and then the servers are more nodes with an icon for the server image. The server images were exported from Visio, and the scaling feature in Weathermap was used to make them all the same width.

**Comment by howardjones** [comment]
Here you go - I wrote a blog post for it:

http://lesser-evil.com/2016/06/rack-diagrams-with-weathermap/
