### ISSUE TITLE
Call to undefined function mysql_connect()

### ISSUE THREAD

**Issue by YATV** [howardjones/network-weathermap#33]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/net.musurit.monitoring/plugins/weathermap/cacti-pick.php:69 Stack trace: #0 {main} thrown in /var/www/net.musurit.monitoring/plugins/weathermap/cacti-pick.php on line 69

I use Nginx + php-fpm ( PHP70 )

**Comment by howardjones** [comment]
This is correct. Cacti itself also doesn't work on PHP 7 either though, partly for the same reason.

The next weathermap release is switching from mysql_xxxx calls to PDO, which will resolve this for the Weathermap Cacti plugin and picker. Cacti 1.0 is doing the same - I doubt there will be a fix for Cacti 0.8.x. The Cacti team's fix at this time is to use PHP 5.6. In particular Ubuntu 16 comes with PHP 7 now, which has highlighted this problem.

**Comment by YATV** [comment]
Cacti 0.8.8g and Cacti SPINE 0.8.8g - work with PHP 7.0 without problem

**Comment by howardjones** [comment]
That's interesting. They didn't for me! :-) And there is a whole thread in the Cacti forum of Ubuntu 16 users with problems.

Anyway, for Weathermap the solution is 0.98a, which is in progress. Removing all the database calls from the plugin takes a while. I hope it will be complete in the next couple of weeks.

**Comment by YATV** [comment]
Hello! Any news?

**Comment by howardjones** [comment]
Making progress! The two cacti plugin parts are very nearly complete. The editor data-picker remains.

**Comment by YATV** [comment]
Many thanks.
I am pleased to be testing)

**Comment by howardjones** [comment]
Sure - I'll let you know :-) Also, I just fired up my Ubuntu 16 vagrant box, and this is the error I get from Cacti 0.8.8.h on it (PHP 7.0.4, mysql 5.7.12) :

    [Tue Jul 19 17:05:10.112827 2016] [:error] [pid 18507] [client 10.0.2.2:56310] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /var/www/html/cacti/lib/adodb/adodb.inc.php on line 866

which is why I was confused that you have it working! It seems that the ADODB bundled with Cacti hits this change in PHP 7.0 [New objects cannot be assigned by reference](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.new-by-ref), and also, the ADODB mysql driver uses the deprecated mysql_* functions, which [don't exist in PHP 7.0](http://php.net/manual/en/migration70.removed-exts-sapis.php)

**Comment by YATV** [comment]
$database_type     = 'mysqli';

**Comment by YATV** [comment]
![image](https://cloud.githubusercontent.com/assets/2369847/16961908/dfabc9b4-4dc5-11e6-9cf7-05103a6b81e9.png)

**Comment by howardjones** [comment]
Even with 'mysqli', I still get the parse error. I don't see why you wouldn't. Very strange. Anyway, PDO is the future.

**Comment by howardjones** [comment]
The database changes are happening in the database-refactor branch, here: 25cd23a0f47200ecb067acb3abd141258000e784

**Comment by malgoe** [comment]
FYI: I'm on 0.8.8f (the APT version for ubuntu 16.04) and it seems to work fine. I can add hosts, create graphs, poll data, everything i'd expect. The only complaint seems to be that 0.8.8f doesn't know about the rrdtool version I have (also APT version), but it still works. PHP7, Ubuntu 16.04. Using spine for polling.

**Comment by howardjones** [comment]
All mysql_* functions are replaced now.
