### ISSUE TITLE
Call to undefined function mysql_real_escape_string()

### ISSUE THREAD

**Issue by YATV** [howardjones/network-weathermap#34]
Fatal error: Uncaught Error: Call to undefined function mysql_real_escape_string() in /var/www/net.musurit.monitoring/plugins/weathermap/weathermap-cacti-plugin-mgmt.php:837 Stack trace: #0 /var/www/net.musurit.monitoring/plugins/weathermap/weathermap-cacti-plugin-mgmt.php(274): add_config('simple.conf') #1 {main} thrown in /var/www/net.musurit.monitoring/plugins/weathermap/weathermap-cacti-plugin-mgmt.php on line 837

I use Nginx + php-fpm (php70)

**Comment by howardjones** [comment]
Same situation as #33

**Comment by howardjones** [comment]
All mysql_* functions are replaced now.
