### ISSUE TITLE
PHP Parse error when installing 

### ISSUE THREAD

**Issue by that1guy15** [howardjones/network-weathermap#37]
Centos 6.8 with PHP 5.3.3 and network-weathermap 0.89 pulled from github today. MRTG only, no Cacti

MRTG and Apache up and polling properly. Working through the install instructions [here](http://network-weathermap.com/manual/0.98/pages/install-cli-editor.html) I try and run weathermap and get the following error:

`PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /var/www/html/weathermap/weathermap on line 60`

Line 60 is 
`if ((new PEAR)->isError($ret)) { die ("Error in command line: " . $ret->getMessage() . "\n (try --help)\n"); }`

I can launch the editor and work with conf files but when I try to generate the html page I get the same error. Both check.php and check-gdbug.php come back perfect.

**Comment by howardjones** [comment]
Which branch did you pull? This is resolved by a recent commit (1dfdf250a9776ecf713fae8032c83ca6bdae6c64) to the 0.97-maintenance branch, which is what will become the next 0.98 release, once I've finished with the work happening in the database-refactor branch.

It's a one-liner change to fix, if you take a look at the commit, and don't want to mess with git branches.

**Comment by that1guy15** [comment]
Thanks for the quick response. Yeah i used the .98 zip link to download. Changed the line mentioned in that commit and it looks to have solved it. 

Thanks!!

**Comment by howardjones** [comment]
Cool!

**Comment by kozfelipe** [comment]
Same. this zip has to be updated: https://github.com/howardjones/network-weathermap/releases/download/version-0.98/php-weathermap-0.98.zip

**Comment by howardjones** [comment]
Please give this version a try: http://network-weathermap.com/files/php-weathermap-0.98a-test2.zip

It's 0.98 updated to work with PHP 7, and should also include this fix.

**Comment by kozfelipe** [comment]
@howardjones thanks for replay

I faced missing files when I tried 0.98a

`/editor-resources/oldeditor.css` references to exclamation.png which is now at `/images` generating 404 error.

I also get `jQuery(...).unload is not a function` from editor.js:44

**Comment by howardjones** [comment]
@kozfelipe Thanks for the feedback! I'm updating now for a test3. I think these are already fixed in the newer 1.0.0 code, but this 0.98a was a quick fix for the PDO/mysql issues. Too quick!
