### ISSUE TITLE
Ubuntu 16 with PHP 5.6 - adding maps fail

### ISSUE THREAD

**Issue by howardjones** [howardjones/network-weathermap#38]
Create an Ubuntu 16 install with PHP 5.6 like this:

```
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0
sudo apt-get install php5.6-common php5.6-cli php5.6-xml php5.6-snmp php5.6-gd
sudo apt install unzip

sudo a2dismod php7.0
sudo a2enmod php5.6

sudo rm /etc/alternatives/php
sudo ln -s /usr/bin/php5.6 /etc/alternatives/php

sudo apt-get install cacti cacti-spine

sudo service apache2 restart
```

Install weathermap 0.98 and add a map.

```
[Mon Sep 05 19:28:27.803109 2016] [:error] [pid 4638] [client 10.0.2.2:61766] PHP Warning:  mysql_insert_id(): A link to the server could not be established in /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php on line 843, referer: http://127.0.0.1:8080/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker
[Mon Sep 05 19:28:27.803115 2016] [:error] [pid 4638] [client 10.0.2.2:61766] PHP Stack trace:, referer: http://127.0.0.1:8080/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker
[Mon Sep 05 19:28:27.803120 2016] [:error] [pid 4638] [client 10.0.2.2:61766] PHP   1. {main}() /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php:0, referer: http://127.0.0.1:8080/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker
[Mon Sep 05 19:28:27.803126 2016] [:error] [pid 4638] [client 10.0.2.2:61766] PHP   2. add_config() /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php:274, referer: http://127.0.0.1:8080/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker
[Mon Sep 05 19:28:27.803132 2016] [:error] [pid 4638] [client 10.0.2.2:61766] PHP   3. mysql_insert_id() /usr/share/cacti/site/plugins/weathermap/weathermap-cacti-plugin-mgmt.php:843, referer: http://127.0.0.1:8080/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker
```

Entry does appear in the weathermap_maps table, but following updates fail (because of no useful value from `mysql_insert_id()` )

**Comment by howardjones** [comment]
The Debian/Ubuntu package configures Cacti to use mysqli instead of mysql. Weathermap uses mysql_ (in this version) throughout. This specific error can be fixed by replacing `mysql_insert_id()` with `db_fetch_insert_id()` on line 843 of `weathermap-cacti-plugin-mgmt.php`, but you will immediately hit other issues with `mysql_real_escape_string` which is more widely used.

The next release replaces all of this with PDO for all database access in Weathermap.

**Comment by jasonkack** [comment]
Is there a work around to manually add a map? because cacti is working great for me in php7 on debian stretch (testing) but weathermap is ignoring me when i try to add a map i created. can I do this manually? that is until you have time to switch to PDO

**Comment by howardjones** [comment]
It's not just adding maps, it's every database call. That doesn't actually affect the `weathermap` command-line tool though. So you can use weathermap with Cacti data, just not the "Manage...Weathermaps" page in Cacti or the "Weathermaps" tab to view the results. You'd need to set up a crontab entry to run the maps. When the plugin *does* work again, you should be able to just add the maps then, and use them as normal, removing the crontab entry again.

The PDO changes are done in github, but there are a couple of other issues to resolve before it can be released. I'm working on those at the moment. Unfortunately that means that the current version you can check out won't really help with PDO either.

**Comment by jasonkack** [comment]
Alright im not gonna get sexy and add this as a cron job yet. ill wait for our release and there is no rush. Keep up the good work and good luck

**Comment by howardjones** [comment]
I think the current database-refactor commit should work for you. I'd be interested in any feedback. It works for me with PHP 5.6, and Cacti 0.8.8.h and uses no mysql_* calls now, only PDO and the Cacti database settings.

Which version of Cacti is working great for you on PHP 7, btw? I get adodb errors on the current release even with mysqli.

**Comment by howardjones** [comment]
All mysql_* code is now replaced with PDO calls.

**Comment by natcha936** [comment]
It's work for me. Now, I can add weathermap already. Thank you
