### ISSUE TITLE
Aggregate maps only show "out" direction data on 0.98

### ISSUE THREAD

**Issue by philip-davis** [howardjones/network-weathermap#39]
It looks like the wmrrd_read_from_real_rrdtool_aggregate function drops first line of RRDTool output, but using RRDtool 1.5.5, there is no leading blank line in the output of the rrdtool command. So I lose the first ("IN:") line. If I comment out lib/datasources/WeatherMapDataSource_rrd.php line 276, it works as expected.

**Comment by howardjones** [comment]
Thanks for the report! That's helpful of it. I'll add a check if there actual is a blank line.

**Comment by howardjones** [comment]
This is changed in the current git repo to automatically detect if the line is there or not.

The 'database-refactor' fork has the latest version here: 
https://github.com/howardjones/network-weathermap/tree/database-refactor/lib/datasources
