### ISSUE TITLE
support for cacti version 1.0?

### ISSUE THREAD

**Issue by dsclassen** [howardjones/network-weathermap#40]
I've been doing some fairly extensive testing with the new cacti v 1.0 (now available on github... yay!) and was wondering about the current compatibility of the network-weathermap plugin.

Is there a particular branch that is more likely to work than another?

I'd be happy to test things out if it would be helpful.

**Comment by howardjones** [comment]
Yes, the database-refactor branch might work for you. I've made some fairly big changes, but the PDO-related stuff needed for Cacti 1.0 should work now. I haven't tried it myself - still working through the remains corners with 0.8.8 :-)

Any wm data plugins that use a database (dsstats, thold, rrd with poller-output) are likely to fail at the moment.

**Comment by howardjones** [comment]
Having got some more details on what is required for Cacti 1.0 support, there is a lot of work involved. The next release will have the PDO changes, but not Cacti 1.0 compatibility. It's likely that there will be a separate plugin install for Cacti 0.8.8, and another for Cacti 1.0, and then weathermap-core or something like that, but all after the next release.

**Comment by howardjones** [comment]
This situation has changed, and the next version *will* have 1.0 support. There is more progress being logged in #58
