### ISSUE TITLE
DS: dsstats plugin doesn't know about PDO

### ISSUE THREAD

**Issue by howardjones** [howardjones/network-weathermap#43]
Need rewrite before 0.98a

**Comment by howardjones** [comment]
Code is updated for PDO. Awaiting testing in Cacti 0.8.8 (dsstats seems to be unavailable for Cacti 1.x)

**Comment by cigamit** [comment]
Howie, dsstats is build into Cacti 1.x.  Part of the 20 or so plugins merged.

**Comment by cigamit** [comment]
Table structure is identical between 0.8.x and 1.x for dsstats.
