### ISSUE TITLE
lib/datasources/WeatherMapDataSource_tabfile.php 

### ISSUE THREAD

**Issue by bkcrisler** [howardjones/network-weathermap#49]
Hi Howard -

I just wanted to post the fix i found for the following error:

`
PHP Warning:  preg_match(): Unknown modifier '1' in /var/www/html/weathermap/lib/datasources/WeatherMapDataSource_tabfile.php on line 41
WARNING: /var/www/html/weathermap/configs//SW_CTX-WTK_CAREN.conf: ReadData: LINK 1/1/1.AUSUTXZM71W-4/1/1.AUSBTX5203W, target: data/SW_CTX-WTK_CAREN.txt on config line 333 of /var/www/html/weathermap/configs//SW_CTX-WTK_CAREN.conf had no valid data, according to WeatherMapDataSource_tabfile
`

basically if $itemname has a forward slash, it will kick back this error.  Quickest fix was to the following function:

`
       function ReadData($targetstring, &$map, &$item)
        {
                $data[IN] = NULL;
                $data[OUT] = NULL;
                $data_time=0;

               // OLD Line
               // $itemname = $item->name;

               // NEW Line
                $itemname = preg_quote($item->name,'/');

                $matches=0;

                $fd=fopen($targetstring, "r");
`

If you have any questions, please reachout bkcrisler@gmail.com

Thanks, 
Bryan

**Comment by howardjones** [comment]
Thanks for the report (and fix)! In the next release, this is actually solved a different way - there's no particular reason for the regexp/preg_match, so it's been replaced with just splitting on the tabs.
