### ISSUE TITLE
Cloned hosts won't appear

### ISSUE THREAD

**Issue by jpobeda** [howardjones/network-weathermap#52]
I'm currently using refactor branch. 

A couple a days ago every time I cloned a host it never showed up because it was only clonning the host by adding the _copy and no directive at all. So the cloned host was on the .conf file but without any other directive than POSISTION.

Today I updated to latest github commits and now it looks like totally broken. Every time I clone a host it does nothing,  nor even creating the new host with _copy on it.

**Comment by howardjones** [comment]
What I saw was that the node got cloned, but with nothing except a position (of 30 30). It's working again in the last commit.
