### ISSUE TITLE
Link bandwidth won't get updated from web editor

### ISSUE THREAD

**Issue by jpobeda** [howardjones/network-weathermap#53]
Hi Howie,

Right after the latest commits I can't no longer update link bw from the web editor. If I do this from the webeditor but by editing the host directives it works.

Branch: database-refactor
![wm issue 53](https://cloud.githubusercontent.com/assets/13456559/20952464/6dd61d90-bc91-11e6-9931-37ce22fd1b0e.png)

**Comment by howardjones** [comment]
Sorry. I'm pulling out some really old stuff, and missed a bit in the editor.

**Comment by jpobeda** [comment]
Fixed. thanks!
