### ISSUE TITLE
Graph color

### ISSUE THREAD

**Issue by V5ctor** [howardjones/network-weathermap#61]
Hello,

I use php WeatherMap plugin and everything works great but when I check graph's link or device, the windows of my graph is in an ugly purple. What do I need to modify to make it white ?
Just below, you can find a screenshot.
http://imgur.com/a/adQMi

Best regards.

Victor

**Comment by bhardgrove** [comment]
Look into defing a scale.  You pick the ranges and the corresponding colors.

**Comment by howardjones** [comment]
The graph isn't drawn by weathermap. Weathermap just takes the graph URL you gave it, and puts it in the HTML output. If you paste that URL into a web browser, is it purple there too? How about in Cacti (or whatever is drawing the graph)?

**Comment by V5ctor** [comment]
I use the plugin in LibreNMS.
I find out, you just have to modify the file /opt/librenms/html/plugins/weathermap/overlib.js and change the hex color values :

if (typeof ol_fgcolor=='undefined') var ol_fgcolor="**#FFFFFF**";
if (typeof ol_bgcolor=='undefined') var ol_bgcolor="**#000000**";
