### ISSUE TITLE
Link's color based on status not percentage

### ISSUE THREAD

**Issue by VictorJ76** [howardjones/network-weathermap#69]
Hello,

I would like to control the colour of the link, actually they change with percentage bandwidth and I want my links be green when the port is Up and red when my port is Down.
I found someone who share this , but no success for me.

```
SCALE ifstatus 0 1.5 255 0 0
SCALE ifstatus 1.5 2.5 0 255 0 
```

http://forums.cacti.net/viewtopic.php?f=16&t=30563

**Comment by howardjones** [comment]
This isn't a support forum.

Please create a thread in the forum, not a bug report here.

And also more information than "no success for me" will be needed there too! (e.g. What does your link configuration look like? Which version of weathermap?)

**Comment by VictorJ76** [comment]
Can you give me a link to the forum. Thank

**Comment by howardjones** [comment]
You gave *me* a link to the forum :-)

http://forums.cacti.net/viewforum.php?f=16

**Comment by VictorJ76** [comment]
There isn't a forum dedicated to phpweathermap ?

**Comment by howardjones** [comment]
There's a mailing list (linked on the website), and the Weathermap forum on the Cacti forums. If you are looking for user support, that's the best place - that's where most users will see it. It's also where other people will benefit from the answer, so it's where I prefer to spend support time for user issues (not bugs). I think this is probably a "how do I" question and not a problem report with the software.
