### ISSUE TITLE
Edit node name from webeditor removes links attached

### ISSUE THREAD

**Issue by jpobeda** [howardjones/network-weathermap#71]
Hi Howie,

I've just relised that when I change node name from webeditor it removes the links attached.

When I click a node to edit it, if do it from that node property window it's fine and it does work properly BUT if from that "Node property window" I click on "EDIT" and make the changes there when I submit the changes it gets rid of the links.

NWM from github on last december I think. But I also tried it with the latest one that's Cacti 1.x compatible and it does the same.

It might be an expected behaviour because it doesn't keep reference to the previous object name or whatever and if that's the cause would be nice to have some WARNING message/prompt.

**Comment by howardjones** [comment]
This is expected - when you edit in the "Edit" window, the editor just replaces the whole config with what you changed. It doesn't read it, or understand it. When you change the 'internal name' field, it knows to look for connected links (and nodes).

I've updated the text above the box to make this clearer.
