### ISSUE TITLE
Info URL and Hover URL not contain base_url

### ISSUE THREAD

**Issue by lichtl** [howardjones/network-weathermap#81]
Hi,

it seems that the Link Properties Info URL and Hover Graph URL do not contain the base_url when populated via cacti-pick. It works fine when it pick the data-source for a Node.

**Comment by howardjones** [comment]
Which version did you test this with? There were some commits last week to correct several problems in the data picker.

**Comment by lichtl** [comment]
I'm on e3b7e61fbe6ec00b6e2d60c949af82b2b14bf7a5

**Comment by howardjones** [comment]
I could have sworn I tested that! I believe it is fixed now... please confirm.

**Comment by lichtl** [comment]
Perfect 👍
Works like a charm
