### ISSUE TITLE
Custom TTF Font artifact when used in conjuction with colored background box

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#87]
In both Editor and after map has been "complied" I have observed an incorrect behavior with Label coloring within box in SVN 1145. Issue doesn't exist in my current old SVN 684 I use in prod.

For your reference I am attaching image demonstrating the behavior in SVN1145:
![background-bleed](https://cloud.githubusercontent.com/assets/11211789/26035882/1c1f1ab4-38a2-11e7-923f-27360cb6d69c.jpg)

Correct behavior from old SVN684:
![svn-684](https://cloud.githubusercontent.com/assets/11211789/26036162/d4b4f32e-38a6-11e7-9ca5-783e3f5e6e59.jpg)

Map sample code:
FONTDEFINE 103 /var/www/html/plugins/weathermap/fonts/URSB.TTF 13

Node configuration:
NODE IIX_VPN_TUNNEL
	LABEL TEXT LABEL #1
	ZORDER 99
	LABELFONT 103
	LABELOUTLINECOLOR none
	LABELBGCOLOR 184 245 222
	ICON 250 150 rbox
	LABELOFFSET 0 -2
	POSITION 197 102

You can try with any TTF font since Github didn't allow me to upload sample font I have referenced in config.

**Comment by howardjones** [comment]
(SVN1145 will be about 2 years old now...) 

I think this is resolved now. Do you agree?

**Comment by ikorzha** [comment]
Howie, awesome job, tested in revision 1147! All fixed. I do agree however that not 1145 but 684 is over 2 years old!
Thank you Howie, I will keep you posted, I'm sure I can find a few once now I can move in my prod to continue testing and to see how this current 1.0.0 weathermap deals with my 21 maps.

**Comment by ikorzha** [comment]
Issue has been resolved :-)
