### ISSUE TITLE
Feature old SVN 684: Individual MAP Run Time in Console Weathermap, Bug: incorrect time stamps in Cacti log for maps runtime

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#88]
Howie, I hope I'm not overshooting my luck here with 2 major issues for me resolved today!
It would be great if you can bring feature that existed on old SVN individual map run time.
Feature existed under Console->Weathermap Screenshot below:
![svn-684-runtime](https://cloud.githubusercontent.com/assets/11211789/26037401/e15be2fe-38bf-11e7-8b62-ce49bcb88200.jpg)
Reason to bring it back: I have a large weathermap installation it is very important to see individual maps runtime so they all fit in 1min polling cycle. I additionally use the feature to identify abnormally run maps simply by looking at their run time and how errors impact it!

Bug:  I just looked at Cacti Log  with weathermap chatty option enabled: I do see that MAP run times are incorrectly stamped: Please see below screenshot time stamps are exactly 4hr off from Cacti's current time:
![time-stamp-issue](https://cloud.githubusercontent.com/assets/11211789/26037499/f5d73d4e-38c1-11e7-8cf5-d92166efd7c1.jpg)

**Comment by howardjones** [comment]
Individual times: yes I agree. They are in the logs currently but not stored in the database yet.

Time stamps: that's really odd. Weathermap doesn't put the time there - it just uses the cacti log function...

**Comment by ikorzha** [comment]
I'm not too concerned with timestamp in log file....But feature is important at least to me :)
I have just migrated 1147 build into production, I have 20 maps that are large, they do run, I do however see new errors to resolve..
I do however see same behavior as on SVN 684, only partial map run on every 1min poll cycle.
I will study the behavior more and formulate and open an issue to work with you..
All I can tell you if I only run 1-2-3-4 maps , all of them run flawlessly every min. When I get to my standard 20 maps some run every min and others run once in random time frame...
I get a complete maps run time every 20-30min....

**Comment by howardjones** [comment]
(I still don't know where you are getting these svn revision numbers from - weathermap hasn't been in an svn repo for a couple of years)

I think I have the runtime working. It was mostly there already. I will commit a new version shortly.

**Comment by ikorzha** [comment]
I have committed to prod your latest patch and confirm that feature now does work in 0.8 branch!
Thank you for bringing it back.
When it comes to revisions, forgive my ignorance on that topic I will simply refer to issues by current revision number going forward.
Thank you for your patience.

**Comment by howardjones** [comment]
I think there is another bug though - if you set these nowarn_XXX in one map, then they will stay set for remaining maps. Nothing clears them out in between maps at the moment!
