### ISSUE TITLE
Latest Weathermap build ignores some of the: "SET nowarn_" config directives

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#89]
Latest Weathermap build ignores some of the: "SET nowarn_" config directives:
I have tested:
SET nowarn_clipping 1  (works)
SET nowarn_WMWARN70 1   (doesn't work)
SET nowarn_WMRRD08 1  (doesn't work)
SET nowarn_WMRRD06 1  (doesn't work)
For my install base "nowarn_WMWARN70" is particularly important since I use it for dynamic VPN tunnel uptime and often enough tunnels not up, I would like to have ability to disable warning msg in Cacti Log.

Sample config file:
```
# Automatically generated by php-weathermap v0.98

TITLE WARNING_ISSUE_89
WIDTH 300
HEIGHT 210

KEYTEXTCOLOR 0 0 0
KEYOUTLINECOLOR 0 0 0
KEYBGCOLOR 255 255 255
BGCOLOR 255 220 220
TITLECOLOR 0 0 0
TIMECOLOR 0 0 0

# All settings for scale DEFAULT
	KEYPOS DEFAULT -1 -1 Traffic Load

	SCALE DEFAULT 0    0      192 192 192   
	SCALE DEFAULT 0    1      255 255 255   
	SCALE DEFAULT 1    10     140 0 255   
	SCALE DEFAULT 10   25     32 32 255   
	SCALE DEFAULT 25   40     0 192 255   
	SCALE DEFAULT 40   55     0 240 0   
	SCALE DEFAULT 55   70     240 240 0   
	SCALE DEFAULT 70   85     255 192 0   
	SCALE DEFAULT 85   100    255 0 0   

# All settings for scale RUNTIME
	SCALE RUNTIME 0    0.1    247 209 74   
	SCALE RUNTIME 0.1  10G    0 255 0   


SET nowarn_clipping 1
SET nowarn_WMWARN70 1
SET nowarn_WMRRD08 1
SET nowarn_WMRRD06 1
SET key_hidepercent_DEFAULT 1
SET community xxxxxxxx
SET rrd_use_poller_output 1

# End of global section


# TEMPLATE-only NODEs:

# TEMPLATE-only LINKs:

# regular NODEs:
NODE node09880
	LABEL Node
	POSITION 278 42

NODE node09980
	LABEL Node
	POSITION 27 42

NODE DR_VPN_UPTIME
	LABEL {node:this:bandwidth_in:%3T}
	LABELOUTLINECOLOR none
	LABELBGCOLOR none
	INFOURL /graph.php?rra_id=all&local_graph_id=62093
	ICON 120 24 box
	TARGET snmp:{map:community}:172.16.95.184:1.3.6.1.4.1.9.9.171.1.2.2.1.8.1.11.49.48.46.49.48.46.49.50.46.49.57.1.14.53.52.46.49.54.52.46.50.48.53.46.49.51.53.4500:-
	USESCALE RUNTIME in percent
	POSITION 148 100

NODE TEST_UPTIME
	LABEL {node:this:bandwidth_in:%3T}
	LABELOUTLINECOLOR none
	LABELBGCOLOR none
	ICON 120 24 box
	TARGET snmp:{map:community}:172.16.95.184:1.3.6.1.4.1.9.9.171.1.2.2.1.8.1.11.49.48.46.49.48.46.49.50.46.49.57.1.15.49.54.50.46.50.48.53.46.50.51.50.46.49.50.57.500:-
	USESCALE RUNTIME in percent
	POSITION 148 158


# regular LINKs:
LINK node09980-node09880
	INFOURL /graph.php?rra_id=all&local_graph_id=51473
	OVERLIBGRAPH /graph_image.php?local_graph_id=51473&rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300
	TARGET /var/www/html/rra/e1z06r2648-vdx6740-pad-a_discards_in_60166.rrd
	NODES node09980 node09880



# That's All Folks!

```
Cacti Log File screenshot after map run:
![issue-89](https://cloud.githubusercontent.com/assets/11211789/26039683/d6b63d64-38eb-11e7-9686-70534b57274e.jpg)

**Comment by jpobeda** [comment]
You may want to remove snmp communities..they don't look dummy ones.

**Comment by ikorzha** [comment]
They didn't represent much of value, but cleaned them any way thanks :)

**Comment by howardjones** [comment]
I think there is another bug though - if you set these nowarn_XXX in one map, then they will stay set for remaining maps. Nothing clears them out in between maps at the moment!

**Comment by ikorzha** [comment]
Howie, i have applied and tested the latest patch 1149 on 2 of my Cacti boxes, results unfortunately the same. I still get no warning suppression. I even tried removing and adding map back with errors, with same results.
Can you please conduct self testing for best assessment...

**Comment by ikorzha** [comment]
Tested with patch 1151 on 2 Cacti boxes, warning suppression still not functioning.

**Comment by ikorzha** [comment]
Exceptional work, thank you I have validated patch 1152 No_warn functions great now!
