### ISSUE TITLE
NWM@Cacti-.1.1.7 Uncaught exception

### ISSUE THREAD

**Issue by jpobeda** [howardjones/network-weathermap#92]
Hi Howie,

Cacti 1.1.7 disables nwm when I add a particular MAP that is working fine on 0.8.8h

This is the error message in clog:

> ERROR PHP ERROR in Plugin 'weathermap': Uncaught exception 'WeathermapInternalFail' with message 'No Bounding Box until points are added' in /usr/share/cacti-1.1.7/plugins/weathermap/lib/WMBoundingBox.class.php:58

The reason was a node with `ICON none`

Should I be a allowed to set an ICON as none or instead of that I should set colors and everything to none to get the same result?
 ```
       AICONOUTLINECOLOR none
        AICONFILLCOLOR none
        LABELOUTLINECOLOR none
        LABELBGCOLOR none
```
Cheers

**Comment by howardjones** [comment]
Is this with a very recent github clone? There was a fix for a similar kind of problem in 6f770d7724b566556bc70661ab7bb543235e8364

**Comment by jpobeda** [comment]
No, it's not. I'll download the latest one and give it a try.

So for the records, ICON none is a valid config?

**Comment by howardjones** [comment]
According to the manual it is.

**Comment by jpobeda** [comment]
I'm sorry for the delay here. Downloaded latest git and it's solved.

Thanks
