### ISSUE TITLE
Latest Build 1169 has introduced  [WMWARN29] warning msgs into the Cacti Log.

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#93]
Latest Build 1169 has introduced  [WMWARN29] warning msgs into the Cacti Log. Previously the same map didn't generate any warning msg of this kind.

Sample msg: 
infrastructure.conf: ColourFromValue: Scale BGP doesn't include a line for 100% while drawing item DX-TEST-VPC_BGP_STATUS [WMWARN29] 
Sample node:
NODE DX-TEST-VPC_BGP_STATUS
	INFOURL /graph.php?rra_id=all&local_graph_id=67303
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=67303
	ICON 20 25 images/arrow_{node:this:inscaletag}.png
	TARGET gauge:/var/www/html/rra/e1z07r11u38-asr1002x-aws-a_snmp_oid_76163.rrd:snmp_oid:-
	USESCALE BGP in percent
	POSITION DX-TEST-VPC 1075 0

# All settings for scale BGP
	SCALE BGP 0    0      255 209 71   2
	SCALE BGP 0    5.9    255 209 71   2
	SCALE BGP 6    6      0 255 0   1

As per screenshot below the value in this node doesn't go above of 6

![image](https://cloud.githubusercontent.com/assets/11211789/26371628/4d847a26-3fc9-11e7-9e49-1f726e10060c.gif)

**Comment by howardjones** [comment]
Does the DEFAULT node include a MAXVALUE line? What does the LABEL look like also?

I don't know what "build 1169" is, but the code has changed slightly for clipping the calculated percentage to a value between 0 and 100 recently.

**Comment by ikorzha** [comment]
I will answer your question in sequence.
1. I use TortoiseSVN to do SVN update with source on my PC, TurtoiseSVN reports build numbers in increments once you push gitHub updates, the latest update you pushed is build 1169.
2. The map in question does have: SET nowarn_clipping 1, I didn't get any WMWARN33 msgs.
3.  Default node in config does include MAXVALUE 100 in config see below.
# TEMPLATE-only NODEs:
NODE DEFAULT
	LABELFONT 1
	MAXVALUE 100

Please let me know if you have further questions.
I can share with you config in question via Cacti forum PM if you need it for testing.
Please let me know.

**Comment by howardjones** [comment]
OK `nowarn_clipping` will stop WMWARN33 messages, so you can't tell if the clipping is happening (I think it might be - would be good to confirm).

If there is no LABEL in the default node, or the problem node, where is "STATUS: 6" coming from?

**Comment by ikorzha** [comment]
I have 2 nodes on top of each other:  see below that is where 6 is coming from :)
I will update my prod  from build 1159 (that what you did on sunday that doesn't have this warn issue) to 1169 now and remove the no warn_clipping and post update in 10min.

NODE DX-TEST-VPC_BGP_STATUS_BOX
	LABEL STATUS: {node:this:bandwidth_in:%0.1k}
	ZORDER 100
	LABELFONT 112
	LABELOUTLINECOLOR none
	INFOURL /graph.php?rra_id=all&local_graph_id=67303
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=67303
	ICON 160 26 box
	TARGET gauge:/var/www/html/rra/e1z07r11u38-asr1002x-aws-a_snmp_oid_76163.rrd:snmp_oid:-
	USESCALE BGP in percent
	LABELOFFSET 14 0
	POSITION DX-TEST-VPC_BGP_STATUS 48 0

NODE DX-TEST-VPC_BGP_STATUS
	INFOURL /graph.php?rra_id=all&local_graph_id=67303
	OVERLIBGRAPH /graph_image.php?rra_id=0&graph_nolegend=true&graph_height=100&graph_width=300&local_graph_id=67303
	ICON 20 25 images/arrow_{node:this:inscaletag}.png
	TARGET gauge:/var/www/html/rra/e1z07r11u38-asr1002x-aws-a_snmp_oid_76163.rrd:snmp_oid:-
	USESCALE BGP in percent
	POSITION DX-TEST-VPC 1075

**Comment by ikorzha** [comment]
I have updated to latest build 1170, and from the map in question did remove 
SET nowarn_clipping 1
I now do get a ton of  [WMWARN33] in addition to [WMWARN29] 
Anything you can do to fix it up please?

ColourFromValue: Clipped 382.13333333334% to 100% for item GEOMNI-PROD_VPC_OUT [WMWARN33]

**Comment by howardjones** [comment]
In those logs, do you see any of those WMWARN33 lines that are actually not correct though? (i.e. `Clipped 6% to 100% for item DX-TEST-VPC_BGP_STATUS`)

The example you gave is correct if you are using a percentage scale and the maxvalue/bandwidth isn't set to include the actual range of values expected from the target. The problem you originally posted would be *incorrect* clipping...

**Comment by ikorzha** [comment]
Howie, can you please help me out,
I have been trying to replicated [WMWARN29] issue on a smaller scale, when i ran 1 or 2 nodes in a separate config I get no warn msg, same node in larger configs report obscene values in log see below:
How could it be when  Cacti reports a steady value of 6 !
![graph](https://cloud.githubusercontent.com/assets/11211789/26413632/90cf4282-407a-11e7-929d-37157b7c9dd3.gif)

Where does this 676.4 from below log file come from?
Can you please take a second look at code, the issue was introduced with this Monday code. I can go and disable WARN29 in config, but I want to get to the bottom of it. That is not right way...


05/24/2017 12:06:48 PM - WEATHERMAP: Poller[0] WARNING: [Map 29] icon-scale-tag.conf: ColourFromValue: Scale BGP doesn't include a line for 676.4 while drawing item SANDBOX [WMWARN29]
05/24/2017 12:06:48 PM - WEATHERMAP: Poller[0] WARNING: [Map 29] icon-scale-tag.conf: ColourFromValue: Scale BGP doesn't include a line for 676.4 while drawing item SANDBOX_BGP_STATUS_BOX [WMWARN29]
05/24/2017 12:06:48 PM - WEATHERMAP: Poller[0] WARNING: [Map 29] icon-scale-tag.conf: ColourFromValue: Scale BGP doesn't include a line for 676.4 while drawing item SANDBOX_BGP_STATUS [WMWARN29]

**Comment by howardjones** [comment]
run with debug logging, and look for ReadData lines. That will tell you what is coming from the data source.

**Comment by ikorzha** [comment]
Howie, I have to admit that I am unable to replicate the issue in test in 1.0.x vs my prod box running 0.8.8h
I'm strongly considering dumping my existing install base on 0.8.8h as I have too many Map run inconsistency problem, data points coming from nowhere in a map where it shouldnt been.
And starting from scratch in 1.0x platform.
I would like to close this case as I am unable to replicate it in 1.0.x
