### ISSUE TITLE
Node relative postioning relative to parent node doesn't function in latest editor build.

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#94]
While editing one of my exisiting node I have discovered that thru the editor I can no longer change position of the node relative to its parent:
In config example below I can no longer change position of NODE SANDBOX thru the editor in node properties thru node coordinates.  It doesn't move.

Lastly as it related to this issue, can you please re-introduce a feature that existed in previous SVN 
LOCK TO NODE:  screen shot below;  It was such a great engineering find that made map development easier!

![lock_ to](https://cloud.githubusercontent.com/assets/11211789/26372515/3ca1fe06-3fcc-11e7-9b08-95baddefb3cd.gif)

```


# Automatically generated by php-weathermap v0.98



WIDTH 400

KEYTEXTCOLOR 0 0 0
KEYOUTLINECOLOR 0 0 0
KEYBGCOLOR 255 255 255
BGCOLOR 255 255 255
TITLECOLOR 0 0 0
TIMECOLOR 0 0 0

# All settings for scale DEFAULT
	KEYPOS DEFAULT -1 -1 Traffic Load

	SCALE DEFAULT 0    0      192 192 192   
	SCALE DEFAULT 0    1      255 255 255   
	SCALE DEFAULT 1    10     140 0 255   
	SCALE DEFAULT 10   25     32 32 255   
	SCALE DEFAULT 25   40     0 192 255   
	SCALE DEFAULT 40   55     0 240 0   
	SCALE DEFAULT 55   70     240 240 0   
	SCALE DEFAULT 70   85     255 192 0   
	SCALE DEFAULT 85   100    255 0 0   


SET testmode 1
SET key_hidezero_DEFAULT 1

# End of global section


# TEMPLATE-only NODEs:

# TEMPLATE-only LINKs:

# regular NODEs:
NODE BGP_SITE_NAME
	LABEL DESCRIPTION
	LABELFONT 5
	AICONFILLCOLOR 191 239 255
	LABELOUTLINECOLOR none
	LABELBGCOLOR none
	ICON 300 30 box
	LABELOFFSET 0 -2
	POSITION 175 178

NODE SANDBOX
	LABEL SANDBOX
	LABELFONT 112
	LABELOUTLINECOLOR none
	LABELBGCOLOR none
	ICON 300 26 box
	LABELOFFSET -64 -1
	POSITION BGP_SITE_NAME 0 37


# regular LINKs:


# That's All Folks!
```

**Comment by howardjones** [comment]
The last commit pulled this code back from the previous version (I figured out how to get a copy of something close to r641). There is one bug in it, which would have always been there. I've opened a ticket for that #95

**Comment by ikorzha** [comment]
Thank you Howie, I would be looking forward to test any potential fix and editor updates.

**Comment by howardjones** [comment]
It should be usable (as much as it was before) right now. The bug is minor, and would have been in the old versions too.

**Comment by ikorzha** [comment]
Tested and is working now thanks:) Build 1170!
Lock to works now too! thanks!
