### ISSUE TITLE
New bug intoduced in editor in latest build (artifacts on top of editor see pic)

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#96]
![artifact](https://cloud.githubusercontent.com/assets/11211789/26403299/c00cc430-405b-11e7-911a-f2d6e1d837f7.gif)

Plus moving a parent node with child locked to it corrupts the parent node and results in PHP errors below:

Notice: Undefined index: node_iconfilename in /var/www/html/plugins/weathermap/editor.php on line 380 Notice: Undefined index: node_iconfilename in /var/www/html/plugins/weathermap/editor.php on line 384 Notice: Undefined index: node_iconfilename in /var/www/html/plugins/weathermap/editor.php on line 385

PS: I will get back to you on WARN26 issue. I'm will create a simple case scenario and get back to you...

**Comment by ikorzha** [comment]
Tested the patch, Howie that you did 40min ago for editor.php original problem reported still there.
Please validate

Notice: Undefined index: node_iconfilename in /var/www/html/plugins/weathermap/editor.php on line 380 Notice: Undefined index: node_iconfilename in /var/www/html/plugins/weathermap/editor.php on line 384 Notice: Undefined index: node_iconfilename in /var/www/html/plugins/weathermap/editor.php on line 385 --NO ICON----ARTIFICIAL ICON--

**Comment by howardjones** [comment]
It works for me... both issues are part of the same problem (outputting part of the page in the wrong order).

**Comment by ikorzha** [comment]
I'm sorry must have been cache issue works now thanks :)
