### ISSUE TITLE
Minor issue: Cacti Log incorrectly displays file path for Weathermap warn msgs

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#97]
Minor issue: Cacti Log incorrectly displays file path for Weathermap warn msgs
Path is broken up:
RRD ReadData: poller_output: <path_rra>/jc_b2b-vpn_5525_sec_snmp_oid_33106.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/html/rra [WMRRD08]

Please see screenshot below:
Cacti Version	0.8.8g
Cacti OS	6.9
PHP Version	5.3.3
SNMP Version	NET-SNMP version: 5.5
RRDTool Version	RRDTool 1.3.x

![log](https://cloud.githubusercontent.com/assets/11211789/26406513/7c96aa12-4066-11e7-9375-c959a987b12e.gif)

**Comment by howardjones** [comment]
I'm not sure which part of this is incorrect - are you saying the file does exist? or that the rra path is wrong, or just the formatting?

The reason the formatting is like that is because that's how cacti stores pathnames in its database, which is what we care about when using poller_output mode. 

```
mysql> select id,local_data_id, data_source_path from data_template_data where data_source_path is not null;
+----+---------------+----------------------------------------+
| id | local_data_id | data_source_path                       |
+----+---------------+----------------------------------------+
| 62 |             3 | <path_rra>/localhost_mem_buffers_3.rrd |
| 63 |             4 | <path_rra>/localhost_mem_swap_4.rrd    |
| 64 |             5 | <path_rra>/localhost_load_1min_5.rrd   |
| 65 |             6 | <path_rra>/localhost_users_6.rrd       |
| 66 |             7 | <path_rra>/localhost_proc_7.rrd        |
+----+---------------+----------------------------------------+
```

**Comment by ikorzha** [comment]
RRA Path is wrong in log..  Then it is is a non issue based on your explanation.

**Comment by ikorzha** [comment]
RRA Path is wrong in log.. Then it is is a non issue based on your explanation.

**Comment by howardjones** [comment]
No, it's not! If it's getting the <path_rra> incorrect, it won't find poller data... are you getting data for that map OK?

**Comment by ikorzha** [comment]
Yes Howie map does function properly, the WARN msgs are for files that "do not exist" so msgs are correct.
My concern was that instead of:
RRD ReadData: poller_output: <path_rra>/jc_b2b-vpn_5525_sec_snmp_oid_33106.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/html/rra [WMRRD08]

It should be: 
RRD ReadData: poller_output: <path_rra>/var/www/html/rra/jc_b2b-vpn_5525_sec_snmp_oid_33106.rrd is not a valid RRD filename within this Cacti install.  [WMRRD08]

Current implementation makes it more difficult to read file path, therefore I wanted to simplify  log reading the way it was functioning previously. If you can correct it please do, if not close the case.

**Comment by howardjones** [comment]
OK, then I'll leave it as is. It is written that way to make it _easier_ to faultfind :-) (you can tell what was in the database, and what comes from the cacti config).

**Comment by howardjones** [comment]
(the important point is that Weathermap is not actually looking for the file on disk, just to match the name you used in the TARGET with an entry in the cacti database)
