### ISSUE TITLE
In latest editor build, 2 nodes are unable to be linked together

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#98]
In latest editor build, 2 nodes are unable to be linked together:
In editor  click: add link, click first node, then when I attempt to select a second node to link, I can't click on it..

**Comment by howardjones** [comment]
Working for me. Is it a node that is relatively positioned where you just moved the parent?

**Comment by ikorzha** [comment]
"Is it a node that is relatively positioned where you just moved the parent?" No it is not
The issue I have in Cacti 0.8.8 works for me in 1.0.x too.

**Comment by howardjones** [comment]
I did test it myself. That's why I said "it's working for me"!

**Comment by ikorzha** [comment]
I'm sorry for false positive, I have cleared browser cache, tested again and you are right it is working.
My fault
